<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE book [

<!ELEMENT book (version+)>
<!ATTLIST book
 filename CDATA #REQUIRED
 title CDATA #REQUIRED
 textStructure CDATA #IMPLIED
>

<!ELEMENT version (divisions, resources*, manuscripts+, text)>
<!ATTLIST version
 title CDATA #REQUIRED
 author CDATA #REQUIRED
 fragment CDATA #IMPLIED
 language CDATA #IMPLIED
>

<!ELEMENT divisions (division)+>

<!ELEMENT division (#PCDATA)>
<!ATTLIST division
 label CDATA #REQUIRED
 delimiter CDATA #IMPLIED
>

<!ELEMENT resources (resource+)>
<!ELEMENT resource (info+, URL?)>
<!ATTLIST resource name CDATA #REQUIRED>

<!ELEMENT info (#PCDATA)>

<!ELEMENT URL (#PCDATA)>

<!ELEMENT manuscripts (ms+)>

<!ELEMENT ms (name, bibliography*)>
<!ATTLIST ms
 abbrev CDATA #REQUIRED
 language CDATA #REQUIRED
 show CDATA #REQUIRED
>

<!ELEMENT name (#PCDATA | sup)*>

<!ELEMENT sup (#PCDATA)>

<!ELEMENT bibliography (#PCDATA | booktitle)*>

<!ELEMENT booktitle (#PCDATA)>

<!ELEMENT text (div+)>

<!ELEMENT div (div | unit)*>
<!ATTLIST div
 number CDATA #REQUIRED
 fragment CDATA #IMPLIED
>

<!ELEMENT unit (reading+)>
<!ATTLIST unit
 id CDATA #REQUIRED
 group CDATA "0"
 parallel CDATA #IMPLIED
>

<!ELEMENT reading (#PCDATA | w)*>
<!ATTLIST reading
 option CDATA #REQUIRED
 mss CDATA #REQUIRED
 linebreak CDATA #IMPLIED
 indent CDATA #IMPLIED
>

<!ELEMENT w (#PCDATA)>
<!ATTLIST w
 morph CDATA #IMPLIED
 lex CDATA #IMPLIED
 style CDATA #IMPLIED
 lang CDATA #IMPLIED
>

]>
<book filename="2Bar" title="2 (Syriac) Baruch">
  <version title="Syriac" author="Daniel M. Gurtner" language="Syriac">
    <divisions>
      <division label="Chapter" delimiter=":"/>
      <division label="Verse"/>
    </divisions>
    <manuscripts>
      <ms abbrev="7aI" language="Syriac" show="yes">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="7aI*" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="7aI1" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Schu" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="CerIt" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="CerI" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="CerII" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Dedering" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Viol" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Gress" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Kmo" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Ryss" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="ChaI" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="ChaII" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Bensly" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Kabisch" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Bog" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="Zimm" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="1515" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="1313" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="1312" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="(?)" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
      <ms abbrev="apud" language="Syriac" show="no">
        <name/>
        <bibliography/>
      </ms>
    </manuscripts>
    <text>
      <div number="1">
        <div number="Superscript">
          <unit id="1" group="0" parallel="">
            <reading option="0" mss="7aI ">ܟܬܒܐ ܕܓܠܝܢܗ ܕܒܪܘܟ ܒܪ ܢܪܝܐ ܀</reading>
          </unit>
          <unit id="2" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܡܦܩ ܡܢ ܝܘܢܝܐ ܠܣܘܪܝܝܐ.</reading>
          </unit>
        </div>
        <div number="1">
          <unit id="3" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܗ̣ܘܐ ܒܫܢܬ ܥܣܪܝܢ ܘܚܡܫ ܕܝܘܟܢܝܐ ܡ̇ܠܟܐ ܕܝܗܘܕܐ̣.</reading>
          </unit>
          <unit id="4" group="0" parallel="">
            <reading option="0" mss="7aI "> ܗܘ̣ܐ ܦܬܓܡܗ ܕܡܪܝܐ ܥܠ ܒܪܘܟ ܒܪ ܢܪܝܐ ܘܐ̣ܡ̣ܪ ܠܗ.</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="5" group="0" parallel="">
            <reading option="0" mss="7aI ">ܚܙ̣ܝܬ</reading>
            <reading option="1" mss="Schu ">ܚܙ̇ܝܬ</reading>
          </unit>
          <unit id="6" group="0" parallel="">
            <reading option="0" mss="7aI ">ܟܠܡܕܡ ܕܥ̇ܒܕ ܠܝ ܥܡܐ ܗܢܐ.</reading>
          </unit>
          <unit id="7" group="0" parallel="">
            <reading option="0" mss="7aI "> ܒܝ̣ܫ̈ܬܐ ܕܥܒ̣ܕܘ ܗܠܝܢ ܬܪܝܢ ܫܒ̈ܛܝܢ ܕܦ̇ܫܘ.</reading>
          </unit>
          <unit id="8" group="0" parallel="">
            <reading option="0" mss="7aI "> ܝܬܝܪ ܡܢ ܥܣܪܐ ܫ̇ܒ̈ܛܝܢ ܕܐܫܬܒܝܘ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="9" group="0" parallel="">
            <reading option="0" mss="CerIt ">ܫܒ̈ܛܐ</reading>
            <reading option="1" mss="7aI ">ܫܒܛܐ</reading>
          </unit>
          <unit id="10" group="0" parallel="">
            <reading option="0" mss="7aI "> ܓܝܪ</reading>
          </unit>
          <unit id="11" group="0" parallel="">
            <reading option="0" mss="CerIt ">ܩܕ̈ܡܝܐ</reading>
            <reading option="1" mss="7aI "> ܩܕܡܝܐ</reading>
          </unit>
          <unit id="12" group="0" parallel="">
            <reading option="0" mss="7aI ">. ܡܢ ܡ̈ܠܟܝܗܘܢ ܐܬܐܠܨܘ ܕܢܚܛܘܢ</reading>
          </unit>
          <unit id="13" group="0" parallel="">
            <reading option="0" mss="7aI ">ܗܠܝܢ ܕܝܢ ܬܪܝܢ ܗ̣ܢܘܢ ܐܠܨ̇ܝܢ ܗܘܘ</reading>
          </unit>
          <unit id="14" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܥ̇ܨܝܢ ܠܡ̈ܠܟܝܗ̇ܘܢ̇ ܕܢܚܛܘܢ.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="15" group="0" parallel="">
            <reading option="0" mss="7aI ">ܡܛܠ ܗܢܐ ܗܐ ܡܝܬܐ ܐܢܐ ܒܝܫ̣ܬܐ</reading>
          </unit>
          <unit id="16" group="0" parallel="">
            <reading option="0" mss="7aI ">ܥܠ ܡܕܝܢܬܐ ܗܕܐ ܘܥܠ ܥܡܘܖ̈ܝܗ̇.</reading>
          </unit>
          <unit id="17" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܬܬܪܝܡ ܡܢ ܩܕܡܝ ܥܕ ܙܒܢܐ.</reading>
          </unit>
          <unit id="18" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܡ̇ܒܕܪ ܐܢܐ ܠܗ ܠܗܢܐ ܥܡܐ ܒܝܢܬ</reading>
          </unit>
          <unit id="19" group="0" parallel="">
            <reading option="0" mss="7aI ">ܥܡ̈ܡܐ ܕܠܥܡ̈ܡܐ ܢܛܐܒ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="20" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܥܡܝ ܕܝܠܝ ܢܬܪܕܐ.</reading>
          </unit>
          <unit id="21" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܢܐܬܐ ܙܒܢܐ ܘܢܒܥܘܢ ܡܨܠܚܢܘܬܗܘܢ ܕܙܒܢܝ̈ܗܘܢ ܀</reading>
          </unit>
        </div>
      </div>
      <div number="2">
        <div number="1">
          <unit id="22" group="0" parallel="">
            <reading option="0" mss="7aI ">ܗܠܝܢ ܕܝܢ ܐܡ̇ܪܬ ܠܟ ܕܬܐܡܪ ܠܐܪܡܝܐ ܘܠܟܠ ܐܝܠܝܢ ܕܕܡ̇ܝܢ ܠܟܘܢ.</reading>
          </unit>
          <unit id="23" group="0" parallel="">
            <reading option="0" mss="7aI ">ܕܬܬܪܚܩܘܢ ܠܟܘܢ ܡܢ ܗܕܐ ܡܕܝܢܬܐ.</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="24" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܛܠ ܕܥ̇ܒ̈ܕܝܟܘܢ ܐܝܬܝܗܘܢ ܠܗܕܐ ܡܕܝܢܬܐ̣ </reading>
          </unit>
          <unit id="25" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܝܟ ܥܡܘܕܐ ܫܪܝܪܐ.	</reading>
          </unit>
          <unit id="26" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܨܠܘ̈ܬܟܘܢ</reading>
          </unit>
          <unit id="27" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܝܟ</reading>
          </unit>
          <unit id="28" group="0" parallel="">
            <reading option="0" mss="7aI "> ܫܘܪܐ ܚܝܠܬܢܐ ܀</reading>
          </unit>
        </div>
      </div>
      <div number="3">
        <div number="1">
          <unit id="29" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܡ̇ܪܬ ܐܘ ܡܪܝܐ ܡܪܝ̣.</reading>
          </unit>
          <unit id="30" group="0" parallel="">
            <reading option="0" mss="7aI "> ܠܗܕܐ ܐܬ̇ܝܬ ܠܥܠܡܐ ܕܐܚ̇ܙܐ</reading>
          </unit>
          <unit id="31" group="0" parallel="">
            <reading option="0" mss="Dedering "> ܒܒܝ̣ܫܬܗ̇</reading>
            <reading option="1" mss="7aI* "> ܒܒܝ̣ܫ̈ܬܗ̇</reading>
          </unit>
          <unit id="32" group="0" parallel="">
            <reading option="0" mss="7aI ">ܕܐܡܝ̣. ܠܐ ܡܪܝ.</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="33" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܢ ܐܫܟ̇ܚܬ ܖ̈ܚܡ̣ܐ ܒܥ̈ܝܢܝܟ̣.</reading>
          </unit>
          <unit id="34" group="0" parallel="">
            <reading option="0" mss="7aI "> ܣܒ ܠܘܩܕܡ̇ ܪܘܚܝ ܕܐ̇ܙܠ ܠܝ ܠܘܬ ܐܒܗ̈ܝ̣.</reading>
          </unit>
          <unit id="35" group="0" parallel="">
            <reading option="0" mss="7aI ">ܘܠܐ ܐܚ̇ܙܐ ܒܐܒܕܢܗ̇ ܕܐܡܝ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="36" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܛܠ ܕܬܖ̈ܬܝܗܝܢ ܐܠܨ̈ܢ ܠܝ ܣ̇ܓܝ.</reading>
          </unit>
          <unit id="37" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܐܩܘܡ ܓܝܪ ܠܩܘܒܠܟ̣.</reading>
          </unit>
          <unit id="38" group="0" parallel="">
            <reading option="0" mss="7aI "> ܠܐ ܡܫܟܚ ܐܢܐ. ܐܠܐ ܐܦ ܠܐ ܕܐ̇ܚܙܐ</reading>
          </unit>
          <unit id="39" group="0" parallel="">
            <reading option="0" mss="Dedering "> ܒܒܝ̣ܫܬܗ̇</reading>
            <reading option="1" mss="7aI "> ܒܒܝ̣ܫܬܗ</reading>
          </unit>
          <unit id="40" group="0" parallel="">
            <reading option="0" mss="7aI ">ܕܐܡܝ ܡܫܟܚܐ ܢܦܫܝ.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="41" group="0" parallel="">
            <reading option="0" mss="7aI ">ܚܕܐ ܕܝܢ ܐܡܪ ܐܢܐ ܩܕܡܝܟ ܡܪܝܐ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="42" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܢܐ ܗܟܝܠ ܗ̇ܘܐ ܡܢ ܒܬܪ ܗܠܝܢ.</reading>
          </unit>
          <unit id="43" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܢ ܓܝܪ ܡܘܒܕ ܐܢܬ ܡܕܝܢܬܟ.</reading>
          </unit>
          <unit id="44" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܡܫܠܡ̣ ܐܢܬ ܐܪܥܟ ܠܣܢܐ̈ܝܢ.</reading>
          </unit>
          <unit id="45" group="0" parallel="">
            <reading option="0" mss="7aI ">ܐܝ̇ܟܢܐ ܬܘܒ ܡܬܕܟܪ ܫܡܗ ܕܐܝܣܪܝܠ.
</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="46" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܘ ܐܝ̇ܟܢܐ ܢܡܠܠ ܥܠ ܬܫܒ̈ܚܬܟ.</reading>
          </unit>
          <unit id="47" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܘ ܠܡ̣ܢܘ</reading>
          </unit>
          <unit id="48" group="0" parallel="">
            <reading option="0" mss="Dedering "> ܡܬ̇ܦܫܩ</reading>
            <reading option="1" mss="7aI "> ܡ̈ܬܦܫܩ</reading>
          </unit>
          <unit id="49" group="0" parallel="">
            <reading option="0" mss="7aI ">  ܡܐ ܕܒܢܡܘܣܟ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="50" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܘ ܕܠܡܐ ܗ̇ܦܟ ܠܗ̇ ܬܨܒܝܬܐ ܠܟܝܢܗ̇.</reading>
          </unit>
          <unit id="51" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܥܠܡܐ ܬܘܒ ܐ̇ܙܠ ܠܗ ܠܫܬܩܐ ܕܡܢ ܩܕܝܡ.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="52" group="0" parallel="">
            <reading option="0" mss="CerIt "> ܘܡܬܢܣܒ</reading>
            <reading option="1" mss="7aI "> ܘܡܬܣܒ</reading>
          </unit>
          <unit id="53" group="0" parallel="">
            <reading option="0" mss="7aI "> ܠܗ ܣܘܓܐܗܝܢ ܕܢܦܫ̈ܬܐ.</reading>
          </unit>
          <unit id="54" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܟܝܢܐ ܕܒܢܝ̈ܢܫܐ ܬܘܒ ܠܐ܁</reading>
          </unit>
          <unit id="55" group="0" parallel="">
            <reading option="0" mss="7aI ">ܡܫܬܡܗ.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="56" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܝ̇ܟܐ ܗܘ ܟܠ ܡܐ</reading>
          </unit>
          <unit id="57" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܐܡ̣ܪܬ</reading>
            <reading option="1" mss="7aI* "> ܕܐܡ̣ܪܬ.</reading>
          </unit>
          <unit id="58" group="0" parallel="">
            <reading option="0" mss="7aI ">ܠܡܘܫܐ ܥܠܝܢ܀܀܀܁</reading>
          </unit>
        </div>
      </div>
      <div number="4">
        <div number="1">
          <unit id="59" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܡ̣ܪ ܠܝ ܡܪܝܐ.</reading>
          </unit>
          <unit id="60" group="0" parallel="">
            <reading option="0" mss="7aI "> ܗܕܐ ܡܕܝܢܬܐ ܠܙܒܢܐ ܡܫܬܠܡܐ.</reading>
          </unit>
          <unit id="61" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܥܡܐ ܡܬܪܕܐ ܒܙܒܢܐ.</reading>
          </unit>
          <unit id="62" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܥܠܡܐ ܠܐ ܡܬܛܥܐ.</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="63" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܘ ܕܠܡܐ ܣܒ̇ܪ ܐܢܬ ܕܗܕܐ̣ ܗܝ ܡܕܝܢܬܐ</reading>
          </unit>
          <unit id="64" group="0" parallel="">
            <reading option="0" mss="7aI "> ܗ̇ܝ ܕܐܡ̇ܪܬ ܥܠܝܗ̇ ܕܥܠ ܦܣ̈ܐ ܕܐܝ̈ܕܝ ܪܫܡܬܟܝ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="65" group="0" parallel="">
            <reading option="0" mss="7aI "> ܠܐ ܗܘܐ ܗܢܐ ܒܢܝܢܐ ܕܗܫܐ ܒܢ̣ܐ ܒܝܢܬܟܘܢ.</reading>
          </unit>
          <unit id="66" group="0" parallel="">
            <reading option="0" mss="7aI "> ܗ̇ܘ ܕܡܬܓܠܐ ܠܘܬܝ.</reading>
          </unit>
          <unit id="67" group="0" parallel="">
            <reading option="0" mss="7aI "> ܗ̇ܘ</reading>
          </unit>
          <unit id="68" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܗܪܟܐ</reading>
            <reading option="1" mss="Schu "> ܕܠܗܪܟܐ</reading>
          </unit>
          <unit id="69" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡ̣ܩܕܡ ܡܥܬܕ.</reading>
          </unit>
          <unit id="70" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܢ ܟܕ ܐܬܚ̣ܫܒܬ ܕܐ̇ܥܒܕ ܦܪܕܝܣܐ.</reading>
          </unit>
          <unit id="71" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܚܘܝܬܗ ܠܐܕܡ ܡܢ ܩܕܡ ܕܠܐ ܢܚܛܐ.</reading>
          </unit>
          <unit id="72" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܟܕ</reading>
          </unit>
          <unit id="73" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܥܒܪ</reading>
            <reading option="1" mss="Viol (?) ">ܥܒܪ</reading>
          </unit>
          <unit id="74" group="0" parallel="">
            <reading option="0" mss="7aI "> ܦܘܩܕܢܐ ܐܬܓܠܙܬ ܠܗ ܡܢܗ.</reading>
          </unit>
          <unit id="75" group="0" parallel="">
            <reading option="0" mss="7aI ">ܐܝܟ ܕܐܦ ܦܪܕܝܣܐ.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="76" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܡܢ ܒܬܪ ܗ̇ܠܝ̣ܢ.</reading>
          </unit>
          <unit id="77" group="0" parallel="">
            <reading option="0" mss="7aI "> ܚܘ̇ܝܬܗ ܠܥ̣ܒܕܝ ܐܒܪܗܡ ܒܠܠܝܐ.</reading>
          </unit>
          <unit id="78" group="0" parallel="">
            <reading option="0" mss="7aI "> ܒܝܬ ܦܠܓ̈ܐ ܕܕܒܚ̈ܐ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="79" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܬܘܒ ܐܦ ܠܡܘܫܐ</reading>
          </unit>
          <unit id="80" group="0" parallel="">
            <reading option="0" mss="7aI ">  ܚܘ̇ܝܬܗ</reading>
            <reading option="1" mss="7aI* ">.  ܚܘ̇ܝܬܗ</reading>
          </unit>
          <unit id="81" group="0" parallel="">
            <reading option="0" mss="7aI ">ܒܛܘܪ ܣܝܢܝ ܟܕ ܚܘ̇ܝܬܗ ܕܡܘܬܗ ܕܡܫܟܢܐ ܘܟܘܠܗܘܢ ܡܐ̈ܢܘܗܝ.</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="82" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܗܫܐ ܗܐ ܢܛܝܪܐ ܠܘܬܝ ܐܝܟ ܕܐܦ ܦܪܕܝܣܐ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="83" group="0" parallel="">
            <reading option="0" mss="7aI "> ܙܠ ܗܟܝܠ ܘܥܒ̇ܕ ܐܝܟ ܕܡܦܩܕ ܐܢܐ ܠܟ ܀ ܀ ܁܁</reading>
          </unit>
        </div>
      </div>
      <div number="5">
        <div number="1">
          <unit id="84" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܥ̇ܢܝܬ ܘܐܡ̇ܪܬ.</reading>
          </unit>
          <unit id="85" group="0" parallel="">
            <reading option="0" mss="7aI "> ܥܬܝܕ ܐܢܐ ܗܟܝܠ ܕܐ̇ܗ̇ܘܐ ܚܝܒ ܒܨܗܝܘܢ</reading>
          </unit>
          <unit id="86" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܢܐܬܘܢ ܣܢܐ̈ܝܟ ܠܗܢܐ ܐܬܪܐ.</reading>
          </unit>
          <unit id="87" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܢܛܐܡܘܢ ܩܘܕܫܟ ܘܢܫܒܘܢ</reading>
          </unit>
          <unit id="88" group="0" parallel="">
            <reading option="0" mss="7aI "> ܝܪܬܘܬܟ</reading>
            <reading option="1" mss="7aI* ">. ܝܪܬܘܬܟ</reading>
          </unit>
          <unit id="89" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܢܫܬܠܛܘܢ</reading>
          </unit>
          <unit id="90" group="0" parallel="">
            <reading option="0" mss="7aI "> ܥܠ ܐܝܠܝܢ ܕܪܚܡ̣ܬ. ܘܢܐܙܠܘܢ ܬܘܒ ܠܐܬܪܐ</reading>
          </unit>
          <unit id="91" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܦܬܟܖ̈ܝܗܘܢ. ܘܢܫܬܒܗܪܘܢ ܩܕܡܝܗܘܢ.</reading>
          </unit>
          <unit id="92" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܡܢܐ ܥܒ̇ܕܬ ܠܗ ܠܫܡܟ ܪܒܐ.</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="93" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܡ̣ܪ ܠܝ ܡܪܝܐ.</reading>
          </unit>
          <unit id="94" group="0" parallel="">
            <reading option="0" mss="7aI "> ܫܡܝ ܘܬܫܒܘܚܬܝ ܥܠܡܐ</reading>
          </unit>
          <unit id="95" group="0" parallel="">
            <reading option="0" mss="Viol ">ܕܥܠܡ̈ܐ </reading>
          </unit>
          <unit id="96" group="0" parallel="">
            <reading option="0" mss="7aI ">ܐܝܬ ܠܗܘܢ.</reading>
          </unit>
          <unit id="97" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܝ̣ܢܝ ܕܝܢ ܒܙܒܢܗ ܢܛ̇ܪ ܙܕܩܗ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="98" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܢܬ ܬܚܙܐ ܒܥܝ̈ܢܝܟ.</reading>
          </unit>
          <unit id="99" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܠܐ ܗܘܐ</reading>
          </unit>
          <unit id="100" group="0" parallel="">
            <reading option="0" mss="7aI "> ܒܥܠܕܒ̈ܒܐ</reading>
            <reading option="1" mss="7aI* (?) ">. ܒܥܠܕܒ̈ܒܐ</reading>
          </unit>
          <unit id="101" group="0" parallel="">
            <reading option="0" mss="7aI "> ܣ̇ܚܦܝܢ ܠܨܗܝܘܢ.</reading>
          </unit>
          <unit id="102" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܠܐ ܡܘܩܕܝܢ ܠܐܘܪܫܠܡ.</reading>
          </unit>
          <unit id="103" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܠܐ</reading>
          </unit>
          <unit id="104" group="0" parallel="">
            <reading option="0" mss="7aI "> ܠܕܝ̇ܢܐ</reading>
            <reading option="1" mss="Gress ">ܠܕܝ̣ܢܐ</reading>
            <reading option="2" mss="Viol "> ܠܕܝ̣ܢܐ</reading>
          </unit>
          <unit id="105" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܫܡܫܝܢ ܠܙܒܢܐ.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="106" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܢܬ ܕܝܢ ܙܠ</reading>
          </unit>
          <unit id="107" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܥ̇ܒܕ</reading>
            <reading option="1" mss="7aI* ">ܘܥܒ̣ܕ </reading>
          </unit>
          <unit id="108" group="0" parallel="">
            <reading option="0" mss="7aI "> ܟܘܠ ܡܕܡ ܕܐܡ̇ܪܬ ܠܟ..</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="109" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܙ̇ܠܬ ܘܕܒ̇ܪܬ ܠܐܪܡܝܐ ܘܠܥܕܘ.</reading>
          </unit>
          <unit id="110" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܠܣܪܝܐ ܘܠܝܒܫ.</reading>
          </unit>
          <unit id="111" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܠܓܕܠܝܐ ܘܠܟܠ</reading>
          </unit>
          <unit id="112" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܝܩܪܘܗܝ</reading>
            <reading option="1" mss="Dedering "> ܡܝܩܖ̈ܘܗܝ</reading>
          </unit>
          <unit id="113" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܥܡܐ.</reading>
          </unit>
          <unit id="114" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܝ̇ܬܝܬ ܐܢܘܢ ܠܢܚܠܐ ܕܩܕܪܘܢ.</reading>
          </unit>
          <unit id="115" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܫܬ̇ܥܝܬ ܠܗܘܢ ܟܠ ܕܐܬܐܡܪ ܠܝ.</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="116" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܪܝܡܘ ܩܠܗܘܢ ܘܒܟܘ ܟܘܠܗܘܢ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="117" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܝ̇ܬܒܢ ܬܡܢ ܘܨܡܢ ܥܕܡܐ ܠܪܡܫܐ ܀ ܀ ܀</reading>
          </unit>
        </div>
      </div>
      <div number="6">
        <div number="1">
          <unit id="118" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܗ̣ܘܐ ܠܝܘܡܐ ܕܡܚܪ̣.</reading>
          </unit>
          <unit id="119" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܗܐ ܚܝܠܐ ܕܟ̈ܠܕܝܐ ܟܪܟܗ̇ ܠܡܕܝܢܬܐ.</reading>
          </unit>
          <unit id="120" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܒܥܕܢ ܪܡܫܐ̣.</reading>
          </unit>
          <unit id="121" group="0" parallel="">
            <reading option="0" mss="7aI "> ܫܒܩܬܗ ܠܥܡܐ ܐܢܐ ܒܪܘܟ.</reading>
          </unit>
          <unit id="122" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܢ̇ܦܩܬ ܘܩ̣ܡ̇ܬ ܠܝ ܥܠ ܒܠܘܛܐ.</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="123" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܡܬܥܝܩ ܗ̇ܘܝܬ ܥܠ ܨܗܝܘܢ</reading>
          </unit>
          <unit id="124" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܡܬܬܢܚ</reading>
            <reading option="1" mss="7aI* ">.ܘܡܬܬܢܚ</reading>
          </unit>
          <unit id="125" group="0" parallel="">
            <reading option="0" mss="7aI "> ܥܠ ܫܒܝܬܐ ܕܐܬܬ ܥܠ ܥܡܐ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="126" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܗܐ ܡܢ ܫܠܝܐ.</reading>
          </unit>
          <unit id="127" group="0" parallel="">
            <reading option="0" mss="7aI "> ܪܘܚܐ ܕܚܝܠܐ ܐܪܝܡܬܢܝ.</reading>
          </unit>
          <unit id="128" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܣܩܬܢܝ ܠܥܠ ܡܢ ܫܘܪܗ̇ ܕܐܘܪܫܠܡ ܠܥܠ.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="129" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܚ̇ܙܝܬ ܘܗܐ ܐܪܒܥܐ ܡܠܐ̈ܟܝܢ ܩܝ̇ܡܝܢ ܥܠ</reading>
          </unit>
          <unit id="130" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܖ̈ܒܥܬܝܗܝܢ ܙܘܝ̈ܬܗ̇ ܕܡܕܝܢܬܐ.</reading>
          </unit>
          <unit id="131" group="0" parallel="">
            <reading option="0" mss="7aI "> ܟܕ ܐܚܝܕܝܢ ܗܘܘ ܚܕ ܚܕ ܡܢܗܘܢ ܠܡܦܐܕܐ ܕܢܘܪܐ ܒܐܝ̈ܕܘܗܝ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="132" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܡܠܐܟܐ ܐܚܪܢܐ ܢܚܬ ܗܘܐ ܡܢ ܫܡܝܐ ܘܐܡ̣ܪ ܠܗܘܢ.</reading>
          </unit>
          <unit id="133" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܚܘܕܘ ܠܡܦܐ̈ܕܝܟܘܢ ܘܠܐ ܬܕܠܩܘܢ.</reading>
          </unit>
          <unit id="134" group="0" parallel="">
            <reading option="0" mss="7aI "> ܥܕܡܐ ܕܐܡ̇ܪ ܠܟܘܢ.</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="135" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܫܬ̇ܕܪܬ ܓܝܪ ܕܠܘܩܕܡ ܐܡ̇ܪ ܠܐܪܥܐ ܡܠܬܐ.</reading>
          </unit>
          <unit id="136" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܣ̇ܝܡ ܠܘܬܗ̇ ܡܕܡ ܕܦܩܕ̇ܢܝ ܡܪܝܐ ܡܪܝܡܐ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="137" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܚܙ̇ܝܬܗ ܕܢܚ̣ܬ ܠܒܝܬ ܩܕܘܫ</reading>
          </unit>
          <unit id="138" group="0" parallel="">
            <reading option="0" mss="7aI "> ܩܘܕ̈ܫܐ.</reading>
            <reading option="1" mss="7aI* (?) ">ܩܘܕ̈ܫܝܢ </reading>
          </unit>
          <unit id="139" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܢܣ̣ܒ ܡܢ ܬܡܢ ܐ̈ܦܝ ܬܪܥܐ̣.</reading>
          </unit>
          <unit id="140" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܦܘܕܐ ܩܕܝܫܐ.</reading>
          </unit>
          <unit id="141" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܚܘܣܝܐ.</reading>
          </unit>
          <unit id="142" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܬܖ̈ܬܝܢ ܠܘܚ̈ܐ.</reading>
          </unit>
          <unit id="143" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܠܒܘܫܐ ܩܕܝܫܐ</reading>
            <reading option="1" mss="Viol "> ܘܠܒܘܫܐ ܩܕܝ̈ܫܐ </reading>
          </unit>
          <unit id="144" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܟܗ̈ܢܐ.</reading>
          </unit>
          <unit id="145" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܦܝܪܡܐ.</reading>
          </unit>
          <unit id="146" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܪܒܥܝܢ ܘܬܡ̈ܢܐ ܟܐ̈ܦܝܢ ܡܝܩܖ̈ܢ.</reading>
          </unit>
          <unit id="147" group="0" parallel="">
            <reading option="0" mss="7aI "> ܗܠܝܢ ܕܠܒ̇ܫ ܗܘܐ ܟܗܢܐ ܘܟܘܠܗܘܢ ܡܐ̈ܢܝ ܩܘܕܫܐ ܕܡܫܟܢܐ.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="148" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܐܡ̣ܪ ܠܐܪܥܐ ܒܩܠܐ ܪܡ̇ܐ.</reading>
          </unit>
          <unit id="149" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܪܥܐ ܐܪܥܐ̣.</reading>
          </unit>
          <unit id="150" group="0" parallel="">
            <reading option="0" mss="7aI "> ܐܪܥܐ ܫܡ̣ܥ ܦܬܓܡܗ </reading>
          </unit>
          <unit id="151" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܐܠܗܐ</reading>
            <reading option="1" mss="7aI* ">. ܕܐܠܗܐ</reading>
          </unit>
          <unit id="152" group="0" parallel="">
            <reading option="0" mss="7aI "> ܚܝܠܬܢܐ.</reading>
          </unit>
          <unit id="153" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܩܒ̇ܠ ܗܠܝܢ ܕܡܓܥܠ ܐܢܐ ܠܟܝ.</reading>
          </unit>
          <unit id="154" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܢܛ̇ܪ ܐܢܘܢ ܥܕܡܐ ܠܙ̈ܒܢܐ ܐܚܖ̈ܝܐ</reading>
          </unit>
          <unit id="155" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܡܐ ܕܐܬܦ̣ܩܕܬ ܬܬܠܝܢ ܐܢܘܢ.</reading>
          </unit>
          <unit id="156" group="0" parallel="">
            <reading option="0" mss="7aI "> ܕܠܐ ܢܫܬܠܛܘܢ ܒܗܘܢ̣ ܢܘܟܖ̈ܝܐ.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="157" group="0" parallel="">
            <reading option="0" mss="7aI "> ܡܛܠ ܕܡ̣ܛܐ ܠܗ ܙܒܢܐ ܕܬܫܬܠܡ ܠܙܒܢܐ ܘܐܘܪܫܠܡ.</reading>
          </unit>
          <unit id="158" group="0" parallel="">
            <reading option="0" mss="7aI "> ܥܕܡܐ ܕܢܬܐܡܪ ܕܬܘܒ ܬܗܦܘܟ ܬܬܩܢ ܠܥܠܡ.</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="159" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܦܬ̤ܚܬ ܐܪܥܐ ܦܘܡܗ̣̇.</reading>
          </unit>
          <unit id="160" group="0" parallel="">
            <reading option="0" mss="7aI "> ܘܒܠ̤ܥܬ ܐܢܘܢ. ܀</reading>
          </unit>
        </div>
      </div>
      <div number="7">
        <div number="1">
          <unit id="161" group="0" parallel="">