<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE book [
<!ELEMENT book (version)+>
<!ATTLIST book filename CDATA #REQUIRED>
<!ATTLIST book title CDATA #REQUIRED>
<!ATTLIST book textStructure CDATA #IMPLIED>
<!ELEMENT version (divisions , resources* , manuscripts+ , text)>
<!ATTLIST version title CDATA #REQUIRED>
<!ATTLIST version author CDATA #REQUIRED>
<!ATTLIST version fragment CDATA #IMPLIED>
<!ATTLIST version language CDATA #IMPLIED>
<!ELEMENT divisions (division)+>
<!ELEMENT division (#PCDATA)>
<!ATTLIST division label CDATA #REQUIRED>
<!ATTLIST division delimiter CDATA #IMPLIED>
<!ELEMENT resources (resource)+>
<!ELEMENT resource (info+ , URL?)>
<!ATTLIST resource name CDATA #REQUIRED>
<!ELEMENT info (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT manuscripts (ms)+>
<!ELEMENT ms (name , bibliography*)>
<!ATTLIST ms abbrev CDATA #REQUIRED>
<!ATTLIST ms language CDATA #REQUIRED>
<!ATTLIST ms show CDATA #REQUIRED>
<!ELEMENT name (#PCDATA | sup)*>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT bibliography (#PCDATA | booktitle)*>
<!ELEMENT booktitle (#PCDATA)>
<!ELEMENT text (div)+>
<!ELEMENT div (div | unit)*>
<!ATTLIST div number CDATA #REQUIRED>
<!ATTLIST div fragment CDATA #IMPLIED>
<!ELEMENT unit (reading)+>
<!ATTLIST unit id CDATA #REQUIRED>
<!ATTLIST unit group CDATA "0">
<!ATTLIST unit parallel CDATA #IMPLIED>
<!ELEMENT reading (#PCDATA | w)*>
<!ATTLIST reading option CDATA #REQUIRED>
<!ATTLIST reading mss CDATA #REQUIRED>
<!ATTLIST reading linebreak CDATA #IMPLIED>
<!ATTLIST reading indent CDATA #IMPLIED>
<!ELEMENT w (#PCDATA)>
<!ATTLIST w morph CDATA #IMPLIED>
<!ATTLIST w lex CDATA #IMPLIED>
<!ATTLIST w style CDATA #IMPLIED>
<!ATTLIST w lang CDATA #IMPLIED>
]>
<book filename="HistRech" title="The History of the Rechabites">
  <version title="Greek" author="Anonymous" language="Greek">
    <divisions>
      <division label="Chapter" delimiter=":"/>
      <division label="Verse"/>
    </divisions>
    <manuscripts>
      <ms abbrev="Charlesworth" language="Greek" show="yes">
        <name>James H. Charlesworth</name>
        <bibliography> James H. Charlesworth, The History of the Rechabites, vol. 1: The Greek Recension (SBLTT 17; Chico, Calif.: Scholars Press, 1982), 14-107.</bibliography>
      </ms>
    </manuscripts>
    <text>
      <div number="Title">
        <div number="0">
          <unit id="1" group="0" parallel="">
            <reading option="0" mss="Charlesworth "> διήγησις ζωσίμου εἰς τὸν βίον τῶν μακάρων κύριε εὐλόγησον</reading>
          </unit>
        </div>
      </div>
      <div number="1">
        <div number="1 ">
          <unit id="2" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">κατ᾽ ἐκεῖνον τὸν καιρὸν ἐκ τῆς ἐρήμου ὑπῆρχεν ἀνήρ τις ὀνόματι ζώσιμος ὅς οὐκ ἔφαγεν ἄρτον ἔτη τεσσαράκοντα καὶ οἶνον οὐκ ἔπιεν· καὶ πρόσωπον ἀνθρώπου οὐχ ἑόρακεν·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="3" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">οὗτος ἦν παρακαλῶν τὸν θεὸν ἵνα ἴδῃ τὴν διοίκησιν τῶν μακάρων·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="4" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἰδοὺ ἄγγελος κυρίου ἀπεστάλη λέγων αὐτῷ· ζώσιμε ἄνθρωπε τοῦ θεοῦ· ἰδοὺ ἀπεστάλην ἀπὸ τοῦ ὑψίστου τοῦ τῶν ὅλων θεοῦ εἰπεῖν σοι ὅτι πεπορεύσῃ εἰς τοὺς μάκαρας· οὐ κατοικήσεις δὲ μετ᾽ αὐτῶν·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="5" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀλλὰ μὴ ὑψώσῃς τὴν καρδίαν σου εἰπών· ἔτη τεσσαράκοντα ἄρτον οὐκ ἔφαγον· ὁ γὰρ λόγος τοῦ θεοῦ ὑπὲρ ἄρτον ἐστιν, καὶ τὸ πνεῦμα τοῦ θεοῦ ὑπὲρ οἶνόν ἐστιν·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="6" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">τὸ γὰρ &lt;εἰπεῖν σε&gt; πρόσωπον ἀνθρώπου οὐκ εἶδον· ἰδοὺ τὸ πρόσωπον τοῦ μεγάλου βασιλέως, ἐγγύς σου·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="7" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ὁ δὲ ζώσιμος ἔφη· οἶδα ὅτι ὅσα ἂν θέλῃ ὁ κύριος δύναται·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="8" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ὁ δὲ ἄγγελος εἶπεν πρὸς αὐτόν· γνῶθι καὶ τοῦτο· ὅτι πρὸς ἓν τῶν γευμάτων αὐτῶν οὐκ εἶ ἄξιος· πλὴν ἀναστὰς πορεύου·</reading>
          </unit>
        </div>
      </div>
      <div number="2">
        <div number="1 ">
          <unit id="9" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἐγὼ δὲ ζώσιμος ἐξελθὼν ἐκ τοῦ σπηλαίου μου τοῦ θεοῦ με προάγοντος ἐπορευόμην μὴ ἐπιστάμενος τὴν ὁδὸν ποῦ ἀπέρχομαι·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="10" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ὁδεύσας ἡμέρας &lt;τεσσαράκοντα ὠλιγοψύχησεν&gt; τὸ πνεῦμά μου καὶ ἐξελύθη τὸ σῶμά μου· καὶ ἀκηδιάσας ἐκαθέσθην καὶ ἤμην προσευχόμενος ἐν τῷ τόπῳ ἐκείνῳ ἐπὶ ἡμέρας τρεῖς·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="11" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἰδοὺ ἦλθεν ζῶον ἐκ τῆς ἐρήμου ὄνομα αὐτῷ κάμηλος· καὶ θήσας τὰ γόνατα εἰς τὴν γῆν· ἔλαβέν με εἰς τὸν τράχηλον αὐτοῦ· καὶ ἐπορεύθη τὴν ἔρημον καὶ ἀπέθετό με·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="12" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἦν ἀλαλαγμὸς τῶν θηρίων ἐκεῖ πολύς· καὶ βρυγμὸς καὶ ἰὸς θανατηφόρος·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="13" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἔμφοβος δὲ γενόμενος, προσηυξάμην πρὸς κύριον· καὶ ἐγένετο σεισμὸς ἐν τῷ τόπῳ ἐκείνῳ πολὺς μετ᾽ ἠχοῦς·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="14" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ &lt;ἐφύσησεν λαῖλαψ&gt; ἀνέμου· καὶ ἐκίνησέν με ἀπὸ τῆς γῆς καὶ ὕψωσέν με εἰς τὸ πτερύγιον αὐτοῦ· καὶ ἤμην προσευχόμενος καὶ ποευόμενος· καὶ ἔστησέν με ἐπὶ τόπου ποταμώδους· καὶ ὄνομα τῷ ποταμῷ εὐμελής·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="15" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἰδοὺ βουλομένου μου· διέρχεσθαι τὸν ποταμόν· ἐβόησέν τις ὡς ἀπὸ τοῦ ὕδατος λέγων· ζώσιμε ἄνθρωπε τοῦ θεοῦ· οὐ δύνασαι διελθεῖν δι᾽ ἐμοῦ· οὐ γὰρ δύναται ὁ ἄνθρωπος τὰ ὕδατά μου διακόψαι· ἀλλ᾽ ἢ κατανόησον ἀπὸ τῶν ὑδάτων ἕως τοῦ οὐρανοῦ·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="16" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ κατανόησας· &lt;εἶδον τεῖχος&gt; νεφέλης κρατοῦν ἀπὸ τῶν ὑδάτων ἕως τοῦ οὐρανοῦ·</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="17" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ εἶπεν ἡ νεφέλη· ζώσιμε ἄνθρωπε τοῦ θεοῦ· δι᾽ ἐμοῦ οὐ διέρχεται πετεινὸν ἐκ τοῦ κόσμου τούτου· οὐδὲ πνοὴ ἀνέμου· οὐδὲ αὐτὸς ὁ ἥλιος· οὐδὲ ὁ πειράζων ἐν τῷ κόσμῳ τούτῳ δύναται διελθεῖν δι᾽ ἐμοῦ·</reading>
          </unit>
        </div>
      </div>
      <div number="3">
        <div number="1 ">
          <unit id="18" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἐγὼ δὲ ἐξέστην ἐπὶ τοῖς ῥήμασιν τούτοις καὶ ἐπὶ τῇ φωνῇ τῇ λεγούσῃ μοι ταῦτα·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="19" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἐμοῦ προσευχομένου ἰδοὺ δύο δένδρα ἀνεφάνησαν ἀπὸ τῆς γῆς καλοείδη καὶ εὐπρεπέστατα· γέμοντα καρπῶν εὐωδίας·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="20" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ κλιθὲν τὸ δένδρον ἐντεῦθεν· ἔλαβεν με ἐπὶ τὴν κορυφὴν αὐτοῦ καὶ ὑψώθη σφόδρα ἀνάμεσον τοῦ ποταμοῦ· καὶ ὑπήντησεν τὸ ἄλλο δένδρον καὶ ἐδέξατό με ἐν τοῖς κλάδοις αὐτοῦ· καὶ κλιθέν· ἔστησέν με ἐπὶ τὴν γῆν</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="21" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀνυψώθησαν τὰ &lt;ἀμφότερα δένδρα·&gt; καὶ ἔστησάν με ἀπὸ τοῦ ποταμοῦ πέραν·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="22" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀνεπαυσάμην ἡμέρας τρεῖς ἐν τῷ τόπῳ ἐκείνῳ· καὶ πάλιν ἀναστὰς ἐπορευόμην· ὅπου δ᾽ ἂν οὐκ ἐγίνωσκον·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="23" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἦν ὁ τόπος ἐκεῖνος πλήρης εὐωδίας πολλῆς· καὶ οὐκ ἦν ὄρος ἔνθα· ἀλλ᾽ ἦν ὁ τόπος ἐκεῖνος πεδινὸς ἄφθορος· ὅλος ἐστεφανωμένος· καὶ πᾶσα ἡ γῆ εὐπρεπής·</reading>
          </unit>
        </div>
      </div>
      <div number="4">
        <div number="1 ">
          <unit id="24" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ εἶδον ἐκεῖ ἄνθρωπον γυμνὸν καθήμενον· καὶ εἶπον ἐν ἑαυτῷ· ἆρα μὴ οὕτως ἐστὶν ὁ πειράζων;</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="25" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἐμνήσθην τῆς φωνῆς τῆς νεφέλης ὅτι εἶπέν μοι· ὅτι οὐ διέρχεται δι᾽ ἐμοῦ οὔτε αὐτὸς ὁ πειράζων ἐν τῷ κόσμῳ·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="26" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ οὕτως θαρρήσας· εἶπον πρὸς αὐτόν· χαίροις ἀδελφέ·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="27" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ αὐτὸς ἀποκριθεὶς εἶπέν μοι· ἡ χάρις μετά σου·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="28" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ πάλιν εἶπον πρὸς αὐτόν· εἰπέ μοι ἄνθρωπε τοῦ θεοῦ, τίς εἶ;</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="29" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀποκριθεὶς εἶπέν μοι· σὺ γὰρ εἶ; τίς εἶ;</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="30" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀποκριθεὶς ἐγὼ εἶπον πάντα τὰ περὶ ἐμοῦ· καὶ ὅτι ηὐξάμην πρὸς κύριον, καὶ ἤνεγκέν με ἐν τῷ τόπῳ τούτῳ·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="31" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀποκριθεὶς εἶπέν μοι· κἀγὼ γινώσκω ὅτι ἄνθρωπος τοῦ θεοῦ εἶ σύ· εἶ &lt;δὲ μή&gt; γε· οὐκ ἂν διῆλθες τὴν νεφέλην καὶ τὸν ποταμὸν καὶ &lt;τὸν ἀέρα.&gt;</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="32" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">τὸ γὰρ πλάτος τοῦ ποταμοῦ· ὡς ἀπὸ μιλίων τριάκοντα· ἡ δὲ νεφέλη ἕως τοῦ οὐρανοῦ· τὸ δὲ βάθος τοῦ ποταμοῦ ἕως τῶν ἀβύσων·</reading>
          </unit>
        </div>
      </div>
      <div number="5">
        <div number="1 ">
          <unit id="33" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ πληρώσας τὸν λόγον τοῦτον ὁ ἄνθρωπος· εἶπεν πάλιν· σὺ ἐκ τῆς ματαιότητος τοῦ κόσμου ἦλθες ὧδε;</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="34" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἐγὼ δὲ εἶπον αὐτῷ· διατί γυμνὸς ὑπάρχεις;</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="35" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ εἶπεν· πόθεν ἔγνως ὅτι γυμνὸς ὑπάρχω; σὺ γὰρ φορῶν δέρματα εκ τῶν προβάτων τῆς γῆς ὑπάρχεις· καὶ αὐτὰ φθειρόμενα σὺν τῷ σώματί σου· ἀλλὰ κατανόησον τῷ ὑψώματι τοῦ οὐρανοῦ καὶ θέασαι τὸ ἔνδυμά μου ποῖόν ἐστιν·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="36" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ θεασάμενος ἐν τῷ οὐρανῷ εἶδον τὸ πρόσωπον αὐτοῦ ὡσεὶ πρόσωπον ἀγγέλου· καὶ τὸ ἔνδυμα αὐτοῦ ὡς ἀστραπὴν ἡ ἐξ ἀνατολῶν εἰς δυσμὰς πορευομένη· καὶ ἐφοβήθην ὅτι υἱὸς θεοῦ ἦν· καὶ ἐγενήθην ἔντρομος πεσὼν ἐπὶ τὴν γῆν·</reading>
          </unit>
        </div>
      </div>
      <div number="6">
        <div number="1 ">
          <unit id="37" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">Καὶ &lt;δεδωκὼς χεῖρα&gt; ἀνέστησέν με λέγων· κἀγὼ εἷς εἰμὶ τῶν μακάρων·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="38" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">δεῦρο ὅπως ἄξω σε πρὸς τοὺς πρεσβυτέρους·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="39" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ κρατήσας τῆς χειρός μου· συμπεριεπάτησέν μοι· καὶ ἤγαγέν με ἐπί τινα ὄχλον καὶ ἦσαν ἐν τῷ ὄχλῳ ἐκείνῳ πρεσβῦται ὅμοιοι υἱοὶ θεοῦ· καὶ ἦσαν παριστάμενοι νεανίσκοι τοῖς πρεσβυτέροις·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="40" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀπελθόντος δὲ ἐμοῦ ἔγγιστα αὐτῶν εἶπαν· οὗτος ἐκ τῆς ματαιότητος τοῦ κόσμου ἐλήλυθεν δεῦτε δεηθῶμεν τοῦ κυρίου καὶ φανερώσει ἡμῖν τὸ μυστήριον τοῦτο·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="41" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">μὴ ἄρα τὸ τέλος ἔφθασεν· ὅτι ἄνθρωπος τῆς ματαιότητος ἦλθεν ὧδε·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="42" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀναστάντες, ἐδεήθησαν τοῦ κυρίου ὁμοθυμαδόν· καὶ ἰδοὺ ἄγγελοι δύο κατέβησαν ἐκ τῶν οὐρανῶν, καὶ εἶπαν· μὴ φοβήθητε τὸν ἄνδρα· ὅτι ἀπέσταλκεν αὐτὸν ὁ θεὸς ἵνα ποιήσῃ ἑπτὰ ἡμέρας· καὶ λάβῃ τὰς διοικήσεις ὑμῶν· καὶ τότε ἐκπορεύεται· καὶ ἀπελεύσεται ἐν τῷ τόπῳ αὐτοῦ·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="43" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">οἱ δὲ ἄγγελοι τοῦ θεοῦ εἰπόντες ταῦτα· ἀνέβησαν εἰς τὸν οὐρανὸν ἐνώπιον τῶν ὀφθαλμῶν ἡμῶν· </reading>
          </unit>
        </div>
      </div>
      <div number="7">
        <div number="1 ">
          <unit id="44" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">τότε παρέδωκάν με οἱ πρεσβύτεροι τῶν μακάρων ἕνα τῶν ὑπηρετῶν λέγοντες· φύλαξον αὐτὸν ἕως ἡμερῶν ἑπτά·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="45" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">παραλαβών με οὖν ὁ ὑπηρέτης· ἀπήγαγέν με εἰς τὸ σπήλαιον αὐτοῦ· καὶ ἤμεθα ὑποκάτω δένδρου διοικούμενοι·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="46" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀπὸ γὰρ ἕκτης ὥρας ἕως ἕκτης τότε ἠσθίομεν· καὶ τὸ ὕδωρ ἐξήρχετο ἀπὸ τοῦ δένδρου γλυκὺ ὑπὲρ τὸ μέλι· καὶ ἐπίνομεν πρὸς τὸν κόρον ἡμῶν, καὶ πάλιν τὸ ὕδωρ ἐδίδυσκεν εἰς τὸν τόπον αὐτοῦ·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="47" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἤκουσεν δὲ πᾶσα ἡ πατριὰ τῶν ἐκεῖσε περὶ ἐμοῦ· ὅτι ἦλθεν ἄνθρωπος ἐκ τῆς ματαιότητος τοῦ κόσμου ὧδε·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="48" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἐσαλεύθη πᾶσα ἡ πατριά· καὶ &lt;ἦλθον ἰδεῖν με&gt; ὅτι ξένον αὐτοῖς ἐφάνη·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="49" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἦσαν οὖν &lt;ἐπερωτῶντές με&gt; πάντα· κἀγὼ ἤμην ἀναγγέλων αὐτοῖς·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="50" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ὠλιγοψύχησα τῷ πνεύματι καὶ τῷ σώματί μου· καὶ παρεκάλεσα τὸν ἄνθρωπον τοῦ θεοῦ τὸν ὑπηρετοῦντά μοι καὶ εἶπον· παρακαλῶ σε ἀδελφέ· ἐὰν ἔλθωσίν τινες ἰδεῖν με ἀνάγγειλον αὐτοῖς ὅτι οὐκ ἔστιν ὧδε ἵνα ἀναπαύσωμαι μικρόν·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="51" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἐβόησεν ὁ ἄνθρωπος τοῦ θεοῦ λέγων· οἴμοι ὅτι ἱστορία τοῦ ἀδὰμ ἐμοὶ ἀνεκεφαλαιώθη· ἐκεῖνον γὰρ διὰ τῆς εὔας ἠπάτησεν ὁ σατανᾶς καὶ ἐμὲ ὁ ἄνθρωπος οὗτος· διὰ τῆς κολακείας, ψεύστην θέλει ἀποκαταστῆσαι· ὄντος αὐτοῦ ὧδε· εἶπέν μοι· ὅτι ψεύσῃ καὶ εἶπε ὅτι οὐκ &lt;ἔστιν ὧδε&gt;·</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="52" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">&lt;ἀπαγάγετέ με&gt; ἐντεῦθεν, ἐπεί· φεύξομαι &lt;ἀπὸ τῆς κώμης·&gt; ἰδοὺ γὰρ βούλεται κατασπείρειν ἐμοὶ σπέρματα τοῦ κόσμου τῆς ματαιότητος·</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="53" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ κατεπανέστησάν μου πᾶς ὁ ὄχλος· καὶ οἱ πρεσβύτεροι καὶ εἶπον· ἄπελθε ἀφ᾽ ἡμῶν ἄνθρωπε οὐκ οἴδαμεν πόθεν ἐλήλυθας πρὸς ἡμᾶς·</reading>
          </unit>
        </div>
        <div number="11">
          <unit id="54" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἐγὼ δὲ ἔκλαυσα κλαυθμῷ μεγάλῳ· καὶ ἀπέστη ἀπ᾽ ἐμοῦ ἡ φρόνησις· καὶ ἐβόησα πρὸς τοὺς πρεσβυτέρους λέγων· συγχωρήσατέ μοι κύριοί μου· καὶ οἱ πρεσβύτεροι καταπαύσαντες· ἡσυχίαν παρέσχον·</reading>
          </unit>
        </div>
        <div number="12">
          <unit id="55" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">τότε ἐξηγησάμην αὐτοῖς τὰ ἀπ᾽ ἀρχῆς ἕως δεῦρο· καὶ ὅτι ἐδεήθην τοῦ θεοῦ ἐλθεῖν πρὸς ὑμᾶς· καὶ κατηξίωσέν με·</reading>
          </unit>
        </div>
        <div number="13">
          <unit id="56" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ οἱ πρεσβύτεροι εἶπον· καὶ νῦν τί &lt;θέλεις ἵνα&gt; ποιήσωμέν σοι·</reading>
          </unit>
        </div>
        <div number="14">
          <unit id="57" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἐγὼ δὲ εἶπον αὐτοῖς· θέλω λαβεῖν ἐξ ὑμῶν τὰς διοικήσεις ὑμῶν·</reading>
          </unit>
        </div>
      </div>
      <div number="8">
        <div number="1 ">
          <unit id="58" group="0" parallel="">
            <reading option="0" mss="Charlesworth "> οἱ δὲ ἐχάρησαν χαρὰν μεγάλην, καὶ ἄραντες πλάκας λιθινάς· κατέγραψαν τοῖς ὄνυξιν αὐτῶν αὐτῶν οὕτως· ἀκούσατε ἀκούσατε υἱοὶ τῶν ἀνθρώπων ἡμῶν τῶν γενομένων μακάρων· ὅτι καὶ ἡμεῖς ἐξ ὑμῶν ἐσμέν·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="59" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ὅτε γὰρ ἐκήρυξεν ἰερεμίας ὁ προφήτης· ὅτι ἡ πόλις ἰερουσαλὴμ παραδοθήσεται εἰς χεῖρας τῶν ὀλοθρευόντων· διέρρηξεν τὰ ἱμάτια αὐτοῦ· καὶ περιεζώσατο σάκκον περὶ τὴν ὀσφὺν αὐτοῦ· καὶ &lt;κατεπάσατο σποδὸν&gt; ἐπὶ τὴν κεφαλὴν αὐτοῦ· καὶ χοῦν ἔλαβεν ἐπὶ τῆς κοίτης αὐτοῦ· καὶ εἶπεν παντὶ τῷ λαῷ ἀποστραφῆναι ἀπὸ τῆς ὁδοῦ αὐτοῦ τῆς πονηρᾶς·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="60" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἤκουσεν δὲ καὶ ὁ πατὴρ ἡμῶν ῥηχὰβ υἱὸς ἀμιναδὰβ καὶ εἶπεν· πρὸς ἡμᾶς· ἀκούσατε υἱοὶ ῥηχὰβ καὶ θυγατέρες τοῦ πατρὸς ὑμῶν· καὶ ἀποδύσασθε τὰ ἱμάτια ὑμῶν ἐκ τοῦ σώματος ὑμῶν καὶ κεράμιον οἴνου οὐ πίεσθε· καὶ ἄρτον ἐκ τοῦ πυρὸς οὐ φάγεσθε· καὶ σίκερα καὶ μέλι οὐ πίεσθε· ἕως τοῦ εἰσακοῦσαι κύριον τῆς δεήσεως ὑμῶν·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="61" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἡμεῖς δὲ εἶπαμεν· ὅτι ἃ ἐνετείλατο ἡμῖν ποιήσωμεν καὶ ἀκουσώμεθα·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="62" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἀπερρίψαμεν ἐκ τοῦ σώματος ἡμῶν τὴν περιβολὴν ἡμῶν· καὶ οὐκ ἐφάγομεν ἄρτον ἐκ πυρός· καὶ οὐκ ἐπίομεν κεράμιον οἴνου· οὔτε μέλι οὔτε σίκερα· καὶ ἐκλαύσαμεν κλαυθμῷ μεγάλῳ· καὶ ἐδεήθημεν τοῦ κυρίου</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="63" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἤκουσεν τῆς προσευχῆς ἡμῶν· καὶ ἀπέστρεψεν τὴν ὀργὴν αὐτοῦ ἀπὸ τῆς πόλεως ἰερουσαλήμ· καὶ ἐγενήθη τῇ πόλει ἰερουσαλὴμ ἔλεος παρὰ κυρίου καὶ ἠλέησεν τὸν λαὸν αὐτοῦ· καὶ ἀπέστρεψεν τὴν ὀργὴν αὐτοῦ τὴν θανατηφόρον·</reading>
          </unit>
        </div>
      </div>
      <div number="9">
        <div number="1 ">
          <unit id="64" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ μετὰ ταῦτα ἀπέθανεν ὁ βασιλεὺς τῆς πόλεως ἰερουσαλήμ· καὶ ἀνέστη βασιλεὺς ἕτερος·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="65" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ συνηθροίσθη πᾶς ὁ λαὸς πρὸς αὐτόν· καὶ κατάδηλον ἐποίησαν πρὸς αὐτὸν περὶ ἡμῶν καὶ εἶπαν· εἰσίν τινες ἐκ τοῦ λαοῦ σου· οἵτινες ἤλλαξαν τὴν ὁδὸν αὐτῶν ἀφ᾽ ἡμῶν·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="66" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καλέσας οὖν αὐτοὺς ὁ βασιλεὺς ἐπηρώτησεν αὐτοὺς ἕνεκεν τίνος πεποιήκασιν τοῦτο·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="67" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ μετεκαλέσατο ἡμᾶς καὶ ἐπηρώτησεν· &lt;τίνες ἐστὲ&gt; καὶ ποίας θρησκείας ἢ ἐκ ποίας πατρίδος;</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="68" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ εἴπαμεν αὐτῷ ἡμεῖς· ἐκ τοῦ λαοῦ σού ἐσμεν τῆς πόλεως ἰερουσαλήμ· καὶ εἶπεν ὁ βασιλεύς· τίνος υἱοί ἐστε· καὶ εἴπαμεν αὐτῷ· υἱοί ἐσμεν παιδός σου· πατρὸς δὲ ἡμῶν ῥηχὰβ υἱοῖ ἰωναδάβ</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="69" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ὅτε ἐκήρυξεν ἰερεμίας ὁ προφήτης ζῶντος τοῦ πατρός σου τοῦ βασιλέως, ἐκήρυξεν θάνατον τῇ πόλει ἰερουσαλὴμ ὅτι ἔτι τριῶν ἡμερῶν καὶ πᾶσα ἡ πόλις θανατωθήσεται·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="70" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀκούσας δὲ ὁ βασιλεὺς ὁ πατήρ σου μετέγνω ἐπὶ ταῖς ἁμαρτίαις αὐτοῦ· καὶ ἐξέθετο δόγμα πᾶσιν τοῦ ἀποστρέψαι ἐκ τῆς ὁδοῦ αὐτῶν τῆς πονηρᾶς·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="71" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀκούσας δὲ ὁ πατὴρ ἡμῶν ὁ παῖς σου· ἐνετείλατο ἡμῖν λέγων· κεράμιον οἴνου οὐ πίεσθε· καὶ ἄρτον ἐκ πυρὸς οὐ φάγεσθε· ἕως τοῦ εἰσακοῦσαι κύριον τῆς δεήσεως ὑμῶν·</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="72" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἡμεῖς δὲ ἐπηκούσαμεν τῆς ἐντολῆς τοῦ πατρὸς ἡμῶν· καὶ ἐγυμνώσαμεν τὰ σώματα ἡμῶν· καὶ οἶνον οὐκ ἐπίομεν· καὶ ἄρτον ἐκ πυρὸς οὐκ ἐφάγομεν· καὶ προσηυξάμεθα πρὸς κύριον περὶ τῆς πόλεως ἰερουσαλήμ·</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="73" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἠλέησεν κύριος τὸν λαὸν αὐτοῦ· καὶ ἀπέσρεψεν τὴν ὀργὴν αὐτοῦ· καὶ εἴδομεν καὶ ὀνήθη ἡ ψυχὴ ἡμῶν καὶ εἶπαμεν· καλὸν εἶναι ἡμᾶς οὕτως·</reading>
          </unit>
        </div>
      </div>
      <div number="10">
        <div number="1 ">
          <unit id="74" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ εἶπεν πρὸς ἡμᾶς ὁ βασιλεύς· καλῶς πεποιήκατε·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="75" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">νῦν οὖν καταμίχθητε μετὰ τοῦ λαοῦ μου· καὶ φάγεσθε ἄρτον· καὶ πίεσθε οἶνον· καὶ δοξάσατε τὸν κύριον ὑμῶν· καὶ ἔσεσθε ὑπακούοντες, θεῷ καὶ βασιλεῖ·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="76" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἡμεῖς δὲ εἴπαμεν ὅτι οὐ παρακούομεν τὸν θεόν·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="77" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">τότε ὀργισθεὶς ὁ βασιλεύς· ἔθετο ἡμᾶς ἐν φυλακῇ· καὶ ἤμεθα διανυκτερεύοντες τὴν νύκταν ἐκείνην·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="78" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἰδοὺ φῶς ἔλαμψεν ἐν τῷ οἰκήματι· καὶ ἄγγελος ἀπεστέγασεν τὴν φυλακήν· καὶ ἐκράτησεν τῆς κορυφῆς ἡμῶν καὶ ἐξήγαγεν ἡμᾶς ἀπὸ τῆς φυλακῆς· καὶ ἔθετο ἡμᾶς εἰς ἀέρα· καὶ ἤνεγκεν ἡμᾶς πρὸς τὸ ὕδωρ τοῦ ποταμοῦ· καὶ εἶπεν πρὸς ἡμᾶς· ὅπου πορεύεται τὸ ὕδωρ πορεύεσθε καὶ ὑμεῖς·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="79" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ ἐβαδίσαμεν σὺν τῷ ὕδατι καὶ σὺν τῷ ἀγγέλῳ·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="80" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ὅτε οὖν ἤνεγκεν ἡμᾶς πρὸς τὸν τόπον τοῦτον· ἐψύγη ὁ ποταμὸς καὶ ἀπώλετο τὸ ὕδωρ· καὶ διερράγη ὁ τόπος· καὶ ἀνῆλθεν ὕδωρ ἀπὸ τῆς ἀβύσσου·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="81" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ περιετείχισεν τὴν πατρίδα ταύτην· καὶ ἦλθεν τεῖχος νεφέλης καὶ ἐπεσκίασεν ἐπάνω τοῦ ὕδατος·</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="82" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ οὐ διέστησεν ἡμᾶς ἐπὶ πᾶσαν τὴν γῆν· ἀλλ᾽ ἔδωκεν ἡμῖν τὴν πατρίδα ταύτην·</reading>
          </unit>
        </div>
      </div>
      <div number="11">
        <div number="1 ">
          <unit id="83" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀκούσατε ἀκούσατε, υἱοὶ τῶν ἀνθρώπων τὴν διοίκησιν τῶν μακάρων·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="84" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἔθετο γὰρ ἡμᾶς ὁ θεὸς ἐπὶ τῆς γῆς ταύτης· καὶ γάρ ἐσμεν εὐσεβεῖς· ἀλλ᾽ οὐκ ἀθάνατοι·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="85" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀνέτειλεν γὰρ ἡ γῆ καρπὸν εὐωδέστατον· καὶ ἐξέρχεται ἐκ τῶν κορμῶν τῶν δένδρων ὕδωρ γλυκὺ ὑπὲρ τὸ μέλι· καὶ ταῦτα ἡμῖν βρῶσις καί πόσις·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="86" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἐσμὲν δὲ καὶ προσευχόμενοι νυκτὸς καὶ ἡμέρας· πᾶσα δὲ ἡ σπουδὴ ἡμῶν τοῦτό ἐστιν·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="87" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">ἀκούσατε υἱοὶ τῶν ἀνθρώπων· ὅτι παρ᾽ ἡμῖν ἄμπελος οὐκ ἔστιν· οὔτε ἄρουρα· οὔτε ἔργα ἐκ ξύλου οὔτε σιδήρου· οὔτε οἶκός ἐστιν ἡμῖν· οὔτε οἰκοδομή οὔτε πῦρ οὔτε ξίφος· οὔτε ἀργὸς σίδηρος οὔτε ἐργάσιμος· οὔτε ἀργύριον οὔτε χρυσίον· οὔτε &lt;ἀὴρ βαρύτατος&gt; οὔτε πικρότατος·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="88" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">οὔτε εἰσὶν ἐξ ἡμῶν λαμβάνοντες ἑαυτοῖς γυναῖκας ἕως οὗ ποιήσωσιν δύο τέκνα·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="89" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ μετὰ τὸ δύο τέκνα ποιῆσαι· ἀφίστανται ἀπ᾽ ἀλλήλων καί εἰσιν ἐν ἁγνείᾳ μὴ γινώσκοντες &lt;ὅτι ἦσάν ποτε ἐν&gt; συνηθείᾳ τοῦ γάμου· ἀλλ᾽ ὡς ὅτι ἀπ᾽ ἀρχῆς ἐν τῇ παρθενίᾳ ὑπάρχοντες·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="90" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">μένει τὸ ἓν τέκνον εἰς τὸν γάμον· καὶ τὸ ἓν εἰς τὴν παρθενίαν· </reading>
          </unit>
        </div>
      </div>
      <div number="12">
        <div number="1 ">
          <unit id="91" group="0" parallel="">
            <reading option="0" mss="Charlesworth ">καὶ οὐκ ἔστιν &lt;ἀριθμὸς χρόνου&gt;· οὔτε ἑβδομάδες οὔτε μῆνες· οὔτε ἐνιαυτός· πᾶσα γὰρ ἡ ἡμέρα ἡμῶν μία ἡμέρα ἐστίν·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="92" group="0" parallel="">