<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE book [
<!ELEMENT book (version)+>
<!ATTLIST book filename CDATA #REQUIRED>
<!ATTLIST book title CDATA #REQUIRED>
<!ATTLIST book textStructure CDATA #IMPLIED>
<!ELEMENT version (divisions , resources* , manuscripts+ , text)>
<!ATTLIST version title CDATA #REQUIRED>
<!ATTLIST version author CDATA #REQUIRED>
<!ATTLIST version fragment CDATA #IMPLIED>
<!ATTLIST version language CDATA #IMPLIED>
<!ELEMENT divisions (division)+>
<!ELEMENT division (#PCDATA)>
<!ATTLIST division label CDATA #REQUIRED>
<!ATTLIST division delimiter CDATA #IMPLIED>
<!ELEMENT resources (resource)+>
<!ELEMENT resource (info+ , URL?)>
<!ATTLIST resource name CDATA #REQUIRED>
<!ELEMENT info (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT manuscripts (ms)+>
<!ELEMENT ms (name , bibliography*)>
<!ATTLIST ms abbrev CDATA #REQUIRED>
<!ATTLIST ms language CDATA #REQUIRED>
<!ATTLIST ms show CDATA #REQUIRED>
<!ELEMENT name (#PCDATA | sup)*>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT bibliography (#PCDATA | booktitle)*>
<!ELEMENT booktitle (#PCDATA)>
<!ELEMENT text (div)+>
<!ELEMENT div (div | unit)*>
<!ATTLIST div number CDATA #REQUIRED>
<!ATTLIST div fragment CDATA #IMPLIED>
<!ELEMENT unit (reading)+>
<!ATTLIST unit id CDATA #REQUIRED>
<!ATTLIST unit group CDATA "0">
<!ATTLIST unit parallel CDATA #IMPLIED>
<!ELEMENT reading (#PCDATA | w)*>
<!ATTLIST reading option CDATA #REQUIRED>
<!ATTLIST reading mss CDATA #REQUIRED>
<!ATTLIST reading linebreak CDATA #IMPLIED>
<!ATTLIST reading indent CDATA #IMPLIED>
<!ELEMENT w (#PCDATA)>
<!ATTLIST w morph CDATA #IMPLIED>
<!ATTLIST w lex CDATA #IMPLIED>
<!ATTLIST w style CDATA #IMPLIED>
<!ATTLIST w lang CDATA #IMPLIED>
]>
<book title="Jubilees" filename="Jub">
  <version title="Greek" author="" language="Greek">
    <divisions>
      <division label="Chapter" delimiter=":"/>
      <division label="Verse"/>
    </divisions>
    <manuscripts>
      <ms abbrev="VanderKam" language="Greek" show="yes">
        <name>VanderKam</name>
        <bibliography>Text: R. H. Charles, The Ethiopic Book of Jubilees (Oxford: Clarendon Press, 1895); A.-M. Denis (ed.), Fragmenta pseudepigraphorum quae supersunt graeca (PVTG 3; Leiden: Brill, 1970) 70-102.
</bibliography>
      </ms>
    </manuscripts>
    <text>
      <div number="1">
        <div number="1">
          <unit id="1" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ τῶν περὶ τὸν πρῶτον ἄνθρωπον, καὶ τῶν μέχρις αὐτοῦ χρόνων, καὶ περὶ τῆς νομοθεσίας τῆς μελλούσης παρ᾽ αὐτοῦ δίδοσθαι τῷ Ἰουδαίων ἔθνει.</reading>
          </unit>
        </div>
      </div>
      <div number="2">
        <div number="1">
          <unit id="2" group="0" parallel="">
            <reading option="0" mss="VanderKam ">διδασκόμενος παρὰ τοῦ ἀρχαγγέλου Γαβριὴλ τὰ περὶ τῆς γενέσεως τοῦ κόσμου . . . </reading>
          </unit>
        </div>
        <div number="2">
          <unit id="3" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ μὲν γὰρ πρώτῃ ἡμέρᾳ ἐποίησε τοὺς ἀνωτέρους οὐρανούς, τὴν γῆν, τὰ ὕδατα, ἐξ ὧν ἐστι χιὼν καὶ κρύσταλλος καὶ χάλαζα καὶ παγετοὶ καὶ δρόσος, τὰ πνεύματα τὰ λειτουργοῦντα ἐνώπιον αὐτοῦ, ἅτινά ἐστι τάδε· ἄγγελοι πρὸ προσώπου, καὶ ἄγγελοι τῆς δόξης, καὶ ἄγγελοι πνευμάτων πνεόντων, ἄγγελοι νεφελῶν καὶ γνόφων, χιόνος καὶ χαλάζης καὶ πάγου, ἄγγελοι φωνῶν, βροντῶν, ἀστραπῶν, ψύχους, καύματος, χειμῶνος, φθινοπώρου, ἔαρος καὶ θέρους, καὶ πάντων τῶν πνευμάτων τῶν κτισμάτων αὐτοῦ τῶν ἐν οὐρανοῖς καὶ ἐν τῇ γῇ, τὰς ἀβύσσους, τήν τε ὑποκάτω τῆς γῆς, καὶ τοῦ χάους, καὶ σκότος, ἑσπέρα καὶ νύξ, τὸ φῶς ἡμέρας τε καὶ ὄρθρου. </reading>
          </unit>
        </div>
        <div number="3">
          <unit id="4" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ταῦτα τὰ ἑπτὰ μέγιστα ἔργα ἐποίησεν ὁ θεὸς ἐν τῇ πρώτῃ ἡμέρᾳ. </reading>
          </unit>
        </div>
        <div number="4">
          <unit id="5" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐν δὲ τῇ δευτέρᾳ τὸ στερέωμα τὸ ἐν μέσῳ τῶν ὑδάτων, καὶ τὴν διαμέρισιν τῶν ἐπάνω τοῦ στερεώματος ὑδάτων, καὶ τῶν ὑποκάτω τοῦ στερεώματος ἐπὶ πρόσωπον πάσης τῆς γῆς. τοῦτο μόνον τὸ ἔργον ἐποίησεν ὁ θεὸς ἐν τῇ δευτέρᾳ ἡμέρᾳ. </reading>
          </unit>
        </div>
        <div number="5">
          <unit id="6" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τρίτῃ δὲ ἡμέρᾳ . . . </reading>
          </unit>
        </div>
        <div number="7">
          <unit id="7" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τὰς θαλάσσας, τοὺς ποταμούς, τὰς πηγὰς καὶ λίμνας, τὰ σπέρματα τοῦ σπόρου, τὰ βλαστήματα, τὰ ξύλα τὰ κάρπιμά τε καὶ ἄκαρπα, τοὺς δρυμούς, καὶ πάντα τὰ φυτὰ κατὰ γένος. ταῦτα τὰ τέσσαρα ἔργα τὰ μέγιστα ἐποίησεν ὁ θεὸς ἐν τῇ τρίτῃ ἡμέρᾳ. </reading>
          </unit>
        </div>
        <div number="8">
          <unit id="8" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ δὲ τετάρτῃ τὸν ἥλιον, τὴν σελήνην, τοὺς ἀστέρας καὶ τὰς τῶν ἄστρων θέσεις καὶ τὰ στοιχεῖα . . . </reading>
          </unit>
        </div>
        <div number="10">
          <unit id="9" group="0" parallel="">
            <reading option="0" mss="VanderKam ">. . . ταῦτα τὰ τρία ἔργα τὰ μεγάλα ἐποίησεν ὁ θεὸς ἐν τῇ τετάρτῃ ἡμέρᾳ. </reading>
          </unit>
        </div>
        <div number="11">
          <unit id="10" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ δὲ πέμπτῃ τὰ κήτη τὰ μεγάλα, τοὺς ἰχθύας καὶ τὰ ἄλλα ἑρπετὰ τὰ ἐν τοῖς ὕδασι, τὰ πετεινά, τὰ πτερωτά. </reading>
          </unit>
        </div>
        <div number="12">
          <unit id="11" group="0" parallel="">
            <reading option="0" mss="VanderKam ">. . . ταῦτα τὰ τρία ἔργα τὰ μεγάλα ἐποίησεν ὁ θεὸς ἐν τῇ πέμπτῃ ἡμέρᾳ. </reading>
          </unit>
        </div>
        <div number="13">
          <unit id="12" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ δὲ ἕκτῃ ἡμέρᾳ τὰ θηρίᾳ, τὰ κτήνη, τὰ ἑρπετὰ τῆς γῆς, </reading>
          </unit>
        </div>
        <div number="14">
          <unit id="13" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τὸν ἄνθρωπον καὶ τοῦ πρώτου ἀνθρώπου καὶ τῶν μετ᾽ ἐκεῖνον. ταῦτα τὰ τέσσαρα μεγάλα ἔργα ἐποίησεν ὁ θεὸς ἐν τῇ ἕκτῃ ἡμέρᾳ. </reading>
          </unit>
        </div>
        <div number="15">
          <unit id="14" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ ἐγένετο πάντα τὰ ἐν ταῖς ἓξ ἡμέραις παρὰ τοῦ θεοῦ ποιηθέντα ἔργα κβʹ. </reading>
          </unit>
        </div>
        <div number="16">
          <unit id="15" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ συνετέλεσεν ὁ θεὸς πάντα ἐν τῇ ἕκτῃ ἡμέρᾳ, ὅσα ἐν τοῖς οὐρανοῖς καὶ ἐν τῇ γῇ, ἐν ταῖς θαλάσσαις καὶ ἐν ταῖς ἀβύσσοις, ἐν τῷ φωτὶ καὶ ἐν τῷ σκότει καὶ ἐν πᾶσι. </reading>
          </unit>
        </div>
        <div number="17">
          <unit id="16" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ ἀνεπαύσατο ὁ θεὸς ἐκ πάντων ἔργων αὐτοῦ ἐν τῇ ἑβδόμῃ ἡμέρα, . . . </reading>
          </unit>
        </div>
        <div number="19">
          <unit id="17" group="0" parallel="">
            <reading option="0" mss="VanderKam ">. . . καὶ ηὐλόγησεν αὐτὴν καὶ ἡγίασεν αὐτὴν καὶ ἐδήλωσεν δι᾽ ἀγγέλου τῷ Μωυσῇ ὅτι . . . </reading>
          </unit>
        </div>
        <div number="20">
          <unit id="18" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ ἐκλέξομαι ἐμαυτῷ ἐκ τοῦ σπέρματος αὐτοῦ λαὸν περιούσιον ἀπὸ πάντων τῶν ἐθνῶν . . . </reading>
          </unit>
        </div>
        <div number="23">
          <unit id="19" group="0" parallel="">
            <reading option="0" mss="VanderKam ">. . . καὶ εἰκοσιδύο κεφάλαια ἀπὸ Ἀδὰμ ἄχρι τοῦ Ἰακώβ. </reading>
          </unit>
        </div>
        <div number="24">
          <unit id="20" group="0" parallel="">
            <reading option="0" mss="VanderKam ">. . . ηὐλογήθη καὶ αὕτη ὑπὸ τοῦ θεοῦ καὶ ἡγιάσθη, καὶ σάββατον ὡς καταπαύσιμος προσηγορεύθη, καὶ ὡς τύπος τῆς ἑβδόμης χιλιοετηρίδος καὶ τῆς τῶν ἁμαρτωλῶν συντελείας . . . </reading>
          </unit>
        </div>
      </div>
      <div number="3">
        <div number="1">
          <unit id="21" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ πρώτῃ ἡμέρᾳ ἑβδομάδος, ἥτις ἦν τρίτη μὲν ἡμέρα τῆς πλάσεως τοῦ Ἀδάμ, ὀγδόῃ δὲ τοῦ πρώτου μηνὸς Νισάν, πρώτῃ δὲ τοῦ Ἀπριλλίου μηνός, καὶ ἕκτῃ τοῦ παρ᾽ Αἰγυπτίοις Φαρμουθί, ὠνόμασεν Ἀδὰμ τὰ ἄγρια θηρία θείῳ τινὶ χαρίσματι. τῇ δευτέρᾳ ἡμέρᾳ τῆς δευτέρας ἑβδομάδος ὠνόμασε τὰ κτήνη. τῇ τρίτῃ ἡμέρᾳ τῆς δευτέρας ἑβδομάδος ὠνόμασε τὰ πετεινά. τῇ τετάρτῃ ἡμέρᾳ τῆς δευτέρας ἑβδομάδος ὠνόμασε τὰ ἑρπετά. τῇ πέμπτῃ ἡμέρᾳ τῆς δευτέρας ἑβδομάδος ὠνόμασε τὰ νηκτά. . . . </reading>
          </unit>
        </div>
        <div number="5">
          <unit id="22" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ ἕκτῃ ἡμέρᾳ τῆς δευτέρας ἑβδομάδος, ἥτις ἦν κατὰ μὲν Ῥωμαίους Ἀπριλλίου ἕκτη, κατὰ δὲ Αἰγυπτίους Φαρμουθὶ ἑνδεκάτη. λαβὼν ὁ θεὸς μέρος τι τῆς πλευρᾶς τοῦ Ἀδὰμ ἔπλασε τὴν γυναῖκα. . . . </reading>
          </unit>
        </div>
        <div number="9">
          <unit id="23" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῇ τεσσαρακοστῇ ἕκτῃ ἡμέρᾳ τῆς κοσμοποιίας, τετάρτῃ ἡμέρᾳ τῆς ἑβδόμης ἑβδομάδος, Παχὼν τεσσαρεσκαιδεκάτῃ, Μαΐου ἐνάτῃ, ἡλίου ὄντος Ταύρῳ καὶ σελήνης Σκορπίῳ κατὰ διάμετρον, ἐν τῇ τῶν Πλειάδων ἐπιτολῇ, εἰσήγαγεν ὁ θεὸς τὸν Ἀδὰμ ἐν τῷ παραδείσῳ κατὰ τὴν τεσσαρακοστὴν ἡμέραν τῆς πλάσεως αὐτοῦ. τῇ ὀγδόῃ ἡμέρᾳ τῆς κοσμοποιίας, τεσσαρακοστῇ τετάρτῃ δὲ τῆς πλάσεως τοῦ Ἀδάμ, ἡμέρᾳ κυριακῇ, Παχὼν ὀκτωκαιδεκάτῃ, Μαΐου τρισκαιδεκάτῃ, μετὰ τρεῖς ἡμέρας τῆς ἐν τῷ παραδείσῳ αὐτοῦ εἰσόδου, ἡλίου ὄντος Ταύρῳ καὶ σελήνης Αἰγοκέρωτι, ἐνετείλατο ὁ θεὸς τῷ Ἀδὰμ ἀπέχεσθαι τῆς βρώσεως τοῦ ξύλου τῆς γνώσεως.
Τῇ ἐνενηκοστῇ τρίτῃ ἡμέρᾳ τῆς κτίσεως, τῇ δευτέρᾳ ἡμέρᾳ τῆς τεσσαρεσκαιδεκάτης ἑβδομάδος, κατὰ τὴν θερινὴν τροπήν, ἡλίου ὄντος καὶ σελήνης Καρκίνῳ, τῇ εἰκοστῇ πέμπτῃ τοῦ Ἰουνίου μηνός, Ἐπιφὶ πρώτῃ, εἰσήχθη ὑπὸ τοῦ θεοῦ ἐν τῷ παραδείσῳ ἡ τοῦ Ἀδὰμ βοηθὸς Εὔα, ἐν τῇ ὀγδοηκοστῇ ἡμέρᾳ τῆς πλάσεως αὐτῆς. </reading>
          </unit>
        </div>
        <div number="33">
          <unit id="24" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἣν ὁ Ἀδὰμ λαβὼν ὠνόμασεν Εὔα, ὃ ἑρμηνεύεται ζωή. </reading>
          </unit>
        </div>
        <div number="10">
          <unit id="25" group="0" parallel="">
            <reading option="0" mss="VanderKam ">διὰ τοῦτο προσέταξεν ὁ θεὸς διὰ Μωϋσέως ἐν τῷ Λευιτικῷ, ἤτοι διὰ τὰς μετὰ τὴν πλάσιν τοῦ χωρισμοῦ αὐτῶν ἡμέρας ἐκ τοῦ παραδείσου, ἐπὶ μὲν ἀρρενογονίας ἀκάθαρτον αὐτὴν εἶναι ἐπὶ τεσσαράκοντα ἡμέρας, </reading>
          </unit>
        </div>
        <div number="11">
          <unit id="26" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐπὶ δὲ θηλυτοκίας ἕως ἡμερῶν πʹ. ἐπειδὴ καὶ Ἀδὰμ τῇ μʹ ἡμέρᾳ τῆς πλάσεως αὐτοῦ εἰσήχθη ἐν τῷ παραδείσῳ, οὗ χάριν καὶ τὰ γεννώμενα τῇ τεσσαρακοστῇ ἡμέρᾳ εἰσφέρουσιν ἐν τῷ ἱερῷ κατὰ τὸν νόμον. ἐπὶ δὲ θήλεος ἀκάθαρτον εἶναι αὐτὴν ἐπὶ ἡμέρας ὀγδοήκοντα, διά τε τὴν ἐν τῷ παραδείσῳ αὐτῆς εἴσοδον τῇ ὀγδοηκοστῇ ἡμέρᾳ καὶ διὰ τὸ ἀκάθαρτον τοῦ θήλεος πρὸς τὸ ἄρσεν. </reading>
          </unit>
        </div>
        <div number="13">
          <unit id="27" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἄφεδρος γὰρ πάλιν οὖσα οὐκ εἰσέρχεται ἕως ἑπτὰ ἡμέρας ἐν τῷ ἱερῷ κατὰ τὸν θεῖον νόμον.</reading>
          </unit>
        </div>
        <div number="16">
          <unit id="28" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὁ Ἀδὰμ ἀπεσόβει τὰ πετεινὰ καὶ ἑρπετά, συνῆγε τὸν καρπὸν ἐν παραδείσῳ, καὶ σὺν τῇ γυναικὶ αὐτοῦ ἤσθιεν αὐτόν.</reading>
          </unit>
        </div>
        <div number="21">
          <unit id="29" group="0" parallel="">
            <reading option="0" mss="VanderKam ">. . . τὸν Ἀδὰμ ἀπροόπτως ἀπὸ τοῦ ξύλου λαβεῖν καὶ φαγεῖν, καὶ μὴ προσχεῖν ὅλως τῷ λόγῳ τῆς Εὔας, ὅτι λειποθυμῶν ἦν ἀπό τε μόχθου καὶ πείνης.</reading>
          </unit>
        </div>
        <div number="23">
          <unit id="30" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὁ ὄφις ἀπὸ κτήνους ἑρπετὸν ἐγένετο, χεῖράς τε καὶ πόδας ἐκέκτητο. ἀφῃρέθη δὲ ταῦτα διὰ τὸ τολμηρῶς εἰς τὸν παράδεισον εἰσελθεῖν, καὶ διὰ τὸ πρῶτος ἀπὸ τοῦ ξύλου λαβεῖν καὶ φαγεῖν.</reading>
          </unit>
        </div>
        <div number="28">
          <unit id="31" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τὰ θηρία καὶ τὰ τετράποδα καὶ τὰ ἑρπετὰ . . . ὁμόφωνα εἶναι πρὸ τῆς παραβάσεως τοῖς πρωτοπλάστοις· διότι . . . ὁ ὄφις ἀνθρωπίνῃ φωνῇ ἐλάλησε τῇ Εὔᾳ . . . </reading>
          </unit>
        </div>
        <div number="32">
          <unit id="32" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ἑβδόμῳ ἔτει παρέβη καὶ τῷ ὀγδόῳ ἐξερρίφησαν τοῦ παραδείσου . . . μετὰ τεσσαράκοντα πέντε ἡμέρας τῆς παραβάσεως, ἐν τῇ ἐπιτολῇ τῶν Πλειάδων. ἐποίησε δὲ ὁ Ἀδὰμ ἐν τῷ παραδείσῳ ἑβδομάδα ἡμερῶν τριακοσίων ἑξήκοντα πέντε. καὶ ἐξεβλήθη σὺν τῇ γυναικὶ Εὔᾳ διὰ τὴν παράβασιν τῇ δεκάτῃ τοῦ Μαΐου μηνός.</reading>
          </unit>
        </div>
        <div number="34">
          <unit id="33" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ὀγδόῳ ἔτει . . . ἔγνω ὁ Ἀδὰμ Εὔαν τὴν γυναῖκα αὐτοῦ.</reading>
          </unit>
        </div>
      </div>
      <div number="4">
        <div number="1">
          <unit id="34" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ἑβδομηκοστῷ ἔτει ἐγεννήθη αὐτοῖς πρωτότοκος υἱὸς ὁ Κάϊν. τῷ ἑβδομηκοστῷ ἑβδόμῳ ἔτει . . . γεγενῆσθαι τὸν δίκαιον Ἄβελ. τῷ ὀγδοηκοστῷ πέμπτῳ ἔτει ἐγεννήθη αὐτοῖς θυγάτηρ, καὶ ὠνόμασαν αὐτὴν Ἀσουάμ. τῷ ἐνενηκοστῷ ἑβδόμῳ ἔτει προσήνεγκε Κάϊν. τῷ ἐνενηκοστῷ ἑνάτῳ ἔτει Ἄβελ ἀνήνεγκε θυσίαν τῷ θεῷ εἰκοστὸν δεύτερον ἔτος ἄγων, κατὰ τὴν πανσέληνον τοῦ ἑβδόμου μηνὸς παρ᾽ Ἑβραίοις, ἤγουν ἐν τῇ σκηνοπηγίᾳ. . . . τὴν Κάϊν καρποφορίαν θυσίαν . . . </reading>
          </unit>
        </div>
        <div number="2">
          <unit id="35" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ αὐτῷ ἐνενηκοστῷ ἐνάτῳ ἔτει ἀνεῖλεν ὁ Κάϊν τὸν Ἄβελ, καὶ ἐπένθησαν αὐτὸν οἱ πρωτόπλαστοι ἑβδομαδικοὺς τέσσαρας, ἤγουν ἔτη εἴκοσι ὀκτώ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="36" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ἑκατοστῷ εἰκοστῷ ἑβδόμῳ ἔτει ὁ Ἀδὰμ καὶ ἡ Εὔα ἀπέθεντο τὸ πένθος.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="37" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ἑκατοστῷ τριακοστῷ πέμπτῳ ἔτει ἔλαβεν ὁ Κάϊν τὴν ἰδίαν ἀδελφὴν Ἀσουνᾶν οὖσαν ἐτῶν νʹ. αὐτὸς δὲ ἦν ἐτῶν ἐξήκοντα πέντε. ὁ μὲν Κάϊν τῇ ἀδελφῇ τῇ μείζονι Σαυὴ οὕτω καλουμένῃ. </reading>
          </unit>
        </div>
        <div number="11">
          <unit id="38" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὁ δὲ Σὴθ τρίτος υἱὸς μετὰ τὸν Ἄβελ γεννηθεὶς τῇ λεγομένῃ αὐτοῦ ἀδελφῇ Ἀζουρᾷ. </reading>
          </unit>
        </div>
        <div number="10">
          <unit id="39" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γεγόνασι δὲ τῷ Ἀδὰμ καὶ ἄλλοι υἱοί . . . ἐννέα μετὰ τοὺς τρεῖς τούτους, ὡς εἶναι αὐτῷ δύο μὲν θυγατέρας, ἄρρενας δὲ δώδεκα, ἕνα μὲν ἀποκτανθέντα, ἕνδεκα δὲ περιλειφθέντας τῷ βίῳ.</reading>
          </unit>
        </div>
        <div number="13">
          <unit id="40" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Ἐνὼς Νωὰ ἡ ἀδελφὴ αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="14">
          <unit id="41" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Καϊὰν Μαωλιθ ἀδελφὴ αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="15">
          <unit id="42" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Μαλελεὴλ Δίνα θυγάτηρ Βαραχιὴλ πατραδέλφου αὐτοῦ. ἐντεῦθεν ἤρξατο ἡ κακομηχανία ἐν κόσμῳ γίνεσθαι, καὶ ἀπ᾽ ἀρχῆς μὲν διὰ τῆς τοῦ Ἀδὰμ παρακοῆς, ἔπειτα δὲ διὰ τῆς τοῦ Κάϊν ἀδελφοκτονίας, νῦν δὲ ἐν χρόνοις τοῦ Ἰάρεδ καὶ ἐπέκεινα φαρμακεία καὶ μαγεία, ἀσέλγεια, μοιχεία τε καὶ ἀδικία.</reading>
          </unit>
        </div>
        <div number="18">
          <unit id="43" group="0" parallel="">
            <reading option="0" mss="VanderKam ">οὗτος (Ἐνώχ) πρῶτος γράμματα μανθάνει καὶ διδάσκει, καὶ θείων μυστηρίων ἀποκαλύψεως ἀξιοῦται.</reading>
          </unit>
        </div>
        <div number="16">
          <unit id="44" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Ἰάρεδ Βαραχὰ θυγάτηρ Ἀσουὴλ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="17">
          <unit id="45" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ ἀριθμητικὴν καὶ γεωμετρίαν καὶ πᾶσαν σοφίαν . . . </reading>
          </unit>
        </div>
        <div number="20">
          <unit id="46" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Ἐνὼχ Ἐᾶνι θυγάτηρ Δανιὴλ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="23">
          <unit id="47" group="0" parallel="">
            <reading option="0" mss="VanderKam ">(Ἐνώχ) εἰς τὸν παράδεισον ἠρπᾶσθαι.</reading>
          </unit>
        </div>
        <div number="27">
          <unit id="48" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Μαθουσάλα Ἐδνὰ θυγάτηρ Ἐζριὴλ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="28">
          <unit id="49" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Λάμεχ Βεθένως θυγάτηρ Βαραχιὴλ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="31">
          <unit id="50" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ αὐτῷ ϡλʹ ἔτει καὶ Κάϊν ἀπέθανεν ἐμπεσόντος ἐπ᾽ αὐτὸν τοῦ οἴκου. λίθοις γὰρ καὶ αὐτὸς τὸν Ἄβελ ἀνεῖλε. πληρωθέντος οὖν ἐνιαυτοῦ μετὰ θάνατον τοῦ Ἀδὰμ τέθνηκεν.</reading>
          </unit>
        </div>
        <div number="31b">
          <unit id="51" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὑπὸ τοῦ Λάμεχ τὸν Κάϊν ἀνῃρῆσθαι ἀκουσίως τοῖχον γὰρ οἰκοδομῶν προσανέτρεψεν αὐτὸν ὄπιθεν ὄντος τοῦ Κάϊν ὃς καὶ ἀνῃρέθη ἀκουσίως.</reading>
          </unit>
        </div>
        <div number="33">
          <unit id="52" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Νῶε Ἐμζάρα θυγάτηρ Βαραχιὴλ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
      </div>
      <div number="5">
        <div number="22">
          <unit id="53" group="0" parallel="">
            <reading option="0" mss="VanderKam ">εἰσῆλθεν πρὸς ἡμᾶς ἡ κιβωτὸς τοῦ θεοῦ . . . τῇ πέμπτῃ τοῦ μηνὸς τοῦ πέμπτου.</reading>
          </unit>
        </div>
      </div>
      <div number="7">
        <div number="1">
          <unit id="54" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τούτῳ τῷ ͵βσναʹ ἔτει . . . Νῶε ἐφύτευσεν ἀμελῶνα ἐν ὄρει Λουβὰρ τῆς Ἀρμενίας.</reading>
          </unit>
        </div>
      </div>
      <div number="8">
        <div number="2">
          <unit id="55" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ͵βφπεʹ ἔτει Καϊνᾶν διοδεύων ἐν τῷ πεδίῳ, </reading>
          </unit>
        </div>
        <div number="3">
          <unit id="56" group="0" parallel="">
            <reading option="0" mss="VanderKam ">εὗρε τὴν γραφὴν τῶν γιγάντων καὶ ἔκρυψε παρ᾽ ἑαυτῷ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="57" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Καϊνᾶν Μελχα θυγάτηρ Μαδαι υἱοῦ Ἰάφεθ.</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="58" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Σαλα Μωαχα θυγάτηρ Χεεδαμ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="59" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Ἐβερ Ἀζουρα θυγάτηρ Νεβρώδ.</reading>
          </unit>
        </div>
      </div>
      <div number="10">
        <div number="1">
          <unit id="60" group="0" parallel="">
            <reading option="0" mss="VanderKam ">μετὰ τὸν κατακλυσμὸν τῷ  ͵βφπβʹ ἔτει τοῦ κόσμου, φθόνῳ κινούμενοι (οἱ ἐγρήγοροι) μετὰ θάνατον ἐπλάνησαν τοὺς υἱοὺς Νῶε· </reading>
          </unit>
        </div>
        <div number="2">
          <unit id="61" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ εὐξαμένου τοῦ Νῶε ἵνα ἀποστῶσιν ἀπ᾽ αὐτῶν </reading>
          </unit>
        </div>
        <div number="7">
          <unit id="62" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὁ κύριος ἐκέλευσε τῷ ἀρχαγγέλῳ Μιχαὴλ βαλεῖν αὐτοὺς εἰς τὴν ἄβυσσον ἄχρι ἡμέρας τῆς κρίσεως· </reading>
          </unit>
        </div>
        <div number="8">
          <unit id="63" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὁ δὲ διάβολος ᾑτήσατο λαβεῖν μοῖραν ἀπ᾽ αὐτῶν πρὸς πειρασμὸν τῶν ἀνθρώπων </reading>
          </unit>
        </div>
        <div number="9">
          <unit id="64" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ ἐδόθη αὐτῷ τὸ δέκατον αὐτῶν κατὰ πρόσταξιν θείαν, ὥστε πειράζειν τοὺς ἀνθρώπους πρὸς δοκιμὴν τῆς ἑκάστου πρὸς θεὸν προαιρέσεως, τὰ δὲ λοιπὰ ἐννέα μέρη ἐβλήθη εἰς τὴν ἄβυσσον.</reading>
          </unit>
        </div>
        <div number="18">
          <unit id="65" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Φαλεχ Δυμνα θυγάτηρ Σεννααρ.</reading>
          </unit>
        </div>
        <div number="21">
          <unit id="66" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐπὶ μγʹ ἔτη ἔμειναν οἰκοδομοῦντες. τὸ ὕψος ͵ευλγʹ πήχεις, καὶ δύω παλαισταί. τὸ πλάτος ἐπὶ σγʹ πλίνθους. τῆς πλίνθου τὸ ὕψος, τρίτον μιᾶς πλίνθου. {τὸ ἔκταμα τοῦ ἑνὸς τοίχου} στάδιοι ιγʹ {καὶ τοῦ ἄλλου} λʹ. </reading>
          </unit>
        </div>
        <div number="21">
          <unit id="67" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐπὶ γὰρ ἔτη τεσσαράκοντα οἰκοδομήσαντες, ἐκείνου (Νεβρὼδ) μάλιστα παρορμῶντος αὐτοὺς εἰς ἀποστασίαν, </reading>
          </unit>
        </div>
        <div number="24">
          <unit id="68" group="0" parallel="">
            <reading option="0" mss="VanderKam ">συνεχύθησαν διαιρεθέντες εἰς πολυγλωσσίαν ὑπὸ τοῦ θεοῦ. ἐκεῖνος (Νεβρὼδ) δὲ ἔμεινεν ἐκεῖ κατοικῶν καὶ μὴ ἀφιστάμενος τοῦ πύργου, βασιλεύων μερικοῦ τινος πλήθους, </reading>
          </unit>
        </div>
        <div number="26">
          <unit id="69" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐφ᾽ ὃν πύργος ἀνέμῳ βιαίῳ . . . καταπεσὼν θείᾳ κρίσει τοῦτον ἐπάταξε.</reading>
          </unit>
        </div>
      </div>
      <div number="11">
        <div number="1">
          <unit id="70" group="0" parallel="">
            <reading option="0" mss="VanderKam ">Ῥαγὰβ γενόμενος ἑκατὸν τριακονταδύο ἐτῶν ἐγέννησε τὸν Σερούχ. </reading>
          </unit>
        </div>
        <div number="2">
          <unit id="71" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐπὶ τούτου οἱ ἄνθρωποι τὸν κατ᾽ ἀλλήλων αὐξήσαντες τῦφον στρατηγούς τε ἑαυτοῖς κατεστήσαντο καὶ βασιλεῖς. καὶ τότε πρώτως πολεμικὰ κατασκευάσαντες ὄργανα πολεμεῖν ἀλλήλοις ἐνήρξαντο.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="72" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Σερουχ Μελχα θυγάτηρ Χαβερ πατραδέλφου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="73" group="0" parallel="">
            <reading option="0" mss="VanderKam ">αὐξηθέντα δὲ τὸν Ναχὼρ ἐδίδαξεν ὁ πατὴρ πάντων ἐπίλυσιν οἰωνῶν, τῶν τε ἐν οὐρανῷ σημείων διακρίσεις καὶ τῶν ἐπὶ γῆς ἁπάντων, καὶ πᾶσαν Χαλδαϊκὴν μαντείαν.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="74" group="0" parallel="">
            <reading option="0" mss="VanderKam ">γυνὴ Ναχὼρ Ἰεσθα θυγάτηρ Νεσθα τοῦ Χαλδαίου.</reading>
          </unit>
        </div>
        <div number="14">
          <unit id="75" group="0" parallel="">
            <reading option="0" mss="VanderKam ">Ναχὼρ δὲ γενόμενος οθʹ ἐτῶν ἐγέννησε τὸν Θάρρα. Νίνου δὲ τοῦ πρώτου βασιλέως τῶν Ἀσσυρίων τεσσαρακοντὸν τρίτον ἄγοντος ἔτος τῆς βασιλείας γεννᾶται Ἀβραάμ . . . Θάρρα δὲ γενόμενος ἐτῶν οʹ ἐγέννησεν ἐκ γυναικὸς Ἔδνας, θυγατρὸς Ἀβραὰμ πατραδέλφου αὐτοῦ, τὸν Ἀβραάμ, ὅντινα ἡ μήτηρ ἐκάλεσεν ἐπ᾽ ὀνόματι τοῦ ἑαυτῆς πατρός· ἔφθη γὰρ ἐκεῖνος πρὸ τῆς τούτου γεννήσεως τετελευτηκέναι.</reading>
          </unit>
        </div>
        <div number="16">
          <unit id="76" group="0" parallel="">
            <reading option="0" mss="VanderKam ">θεοφιλὴς δὲ ὢν καὶ τοῖς κτίσμασι τὸν νοῦν ἑαυτοῦ μὴ καταδεξάμενος ἐᾶσαι ἐνδιατρίβειν, </reading>
          </unit>
        </div>
        <div number="17">
          <unit id="77" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἀλλ᾽ ἐπὶ τὸν γενεσιουργὸν ἐκ τῆς τῶν κτισμάτων ἀναχθεὶς καλλονῆς θείας ἐλλάμψεως ἠξιώθη, ἔτι διατρίβων ἐν τῇ πατρίδι . . .</reading>
          </unit>
        </div>
      </div>
      <div number="12">
        <div number="9">
          <unit id="78" group="0" parallel="">
            <reading option="0" mss="VanderKam ">Σάρα θυγάτηρ ἦν τοῦ Ἀρρὰν ἀδελφὴ τῆς Μέλχας καὶ τοῦ Λώτ . . .</reading>
          </unit>
        </div>
        <div number="12">
          <unit id="79" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τῷ ͵γτογʹ ἔτει τοῦ κόσμου, Ἀβραὰμ δὲ ξαʹ, ἐνεπύρισεν Ἀβραὰμ τὰ εἴδωλα τοῦ πατρὸς αὐτοῦ, </reading>
          </unit>
        </div>
        <div number="14">
          <unit id="80" group="0" parallel="">
            <reading option="0" mss="VanderKam ">καὶ συγκατεκαύθη αὐτοῖς Ἀρρὰν θέλων σβέσαι τὸ πῦρ ἐν νυκτί. καὶ ἐξῆλθε Θαρὰ σὺν Ἀβραὰμ τοῦ ἐλθεῖν εἰς γῆν Χαναάν, καὶ μεταγνοὺς ᾤκησεν ἐν Χαρρὰν εἰδωλομανῶν ἕως θανάτου αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="26">
          <unit id="81" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ὁ ἄγγελος ὁ λαλῶν τῷ Μωϋσῇ εἶπεν αὐτῷ, ὅτι τὸν Ἀβραὰμ ἐγὼ ἐδίδαξα τὴν Ἑβραΐδα γλῶσσαν κατὰ τὴν ἀπ᾽ ἀρχῆς κτίσεως λαλεῖν τὰ πάτρια πάντα . . . </reading>
          </unit>
        </div>
      </div>
      <div number="15">
        <div number="17">
          <unit id="82" group="0" parallel="">
            <reading option="0" mss="VanderKam ">οὗτος ὁ Ἀβραὰμ ἐτῶν ρʹ ἐγέννησεν τὸν Ἰσαάκ. </reading>
          </unit>
        </div>
      </div>
      <div number="16">
        <div number="9">
          <unit id="83" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐκ τοῦ Λὼτ Μωαβήται καὶ Ἀμανίται σπέρμα κατάρατον ἐκ παρανόμου μίξεως.</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="84" group="0" parallel="">
            <reading option="0" mss="VanderKam ">μετὰ ταῦτα τῆς κατὰ Μαβρῆ δρυὸς ἀπαναστὰς ὁ Ἀβραὰμ ἐπὶ τὸ φρέαρ κατασκηνοῖ τοῦ ὅρκου.</reading>
          </unit>
        </div>
        <div number="21">
          <unit id="85" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἑαυτῷ δὲ ἰδίᾳ καὶ τοῖς οἰκέταις αὐτοῦ κατὰ συγγενείας πηξάμενος σκηνάς, τότε πρῶτον Ἀβραὰμ τῆς σκηνοπηγίας ἐπὶ ἑπτὰ ἡμέρας ἐπιτελεῖ τὴν ἑορτήν . . . </reading>
          </unit>
        </div>
        <div number="31">
          <unit id="86" group="0" parallel="">
            <reading option="0" mss="VanderKam ">πρῶτος Ἀβραὰμ ἐκύκλου τὸ θυσιαστήριον κλάδοις φοινίκων καὶ ἐλαιῶν.</reading>
          </unit>
        </div>
      </div>
      <div number="17">
        <div number="15">
          <unit id="87" group="0" parallel="">
            <reading option="0" mss="VanderKam ">τὸν Ἰσαὰκ ἐτῶν κεʹ . . . εἶναι ὅτε πρὸς θυσίαν ἀνήχθη.</reading>
          </unit>
        </div>
        <div number="16">
          <unit id="88" group="0" parallel="">
            <reading option="0" mss="VanderKam ">Μαστιφὰμ ὁ ἄρχων τῶν δαιμονίων . . . προσελθὼν τῷ θεῷ εἶπεν, εἰ ἀγαπᾷ σε Ἀβραάμ, θυσάτω σοι τὸν υἱὸν αὐτοῦ.</reading>
          </unit>
        </div>
      </div>
      <div number="18">
        <div number="13">
          <unit id="89" group="0" parallel="">
            <reading option="0" mss="VanderKam ">εἰς ἐκεῖνον δὲ τὸν τόπον . . . τὸν Ἀβραὰμ οἰκοδομῆσαι ἔνθα Δαβὶδ ὕστερον ἱδρύσατο τὸ ἱερόν.</reading>
          </unit>
        </div>
      </div>
      <div number="19">
        <div number="11">
          <unit id="90" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐγέννησεν πάλιν Ἀβραὰμ ἐκ τῆς ἐσχάτης αὐτοῦ γυναικὸς Χετούρας υἱοὺς πέντε.</reading>
          </unit>
        </div>
        <div number="13">
          <unit id="91" group="0" parallel="">
            <reading option="0" mss="VanderKam ">ἐτῶν δὲ ξʹ ὃν ὁ Ἰσαὰκ ἐγέννησεν τὸν Ἰακώβ.</reading>
          </unit>
        </div>
      </div>
      <div number="22">
        <div number="4">
          <unit id="92" group="0" parallel="">