<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE book [

<!ELEMENT book (version+)>
<!ATTLIST book
 filename CDATA #REQUIRED
 title CDATA #REQUIRED
 textStructure CDATA #IMPLIED
>

<!ELEMENT version (divisions, resources*, manuscripts+, text)>
<!ATTLIST version
 title CDATA #REQUIRED
 author CDATA #REQUIRED
 fragment CDATA #IMPLIED
>

<!ELEMENT divisions (division)+>

<!ELEMENT division (#PCDATA)>
<!ATTLIST division
 label CDATA #REQUIRED
 delimiter CDATA #IMPLIED
>

<!ELEMENT resources (resource+)>
<!ELEMENT resource (info+, URL?)>
<!ATTLIST resource name CDATA #REQUIRED>

<!ELEMENT info (#PCDATA)>

<!ELEMENT URL (#PCDATA)>

<!ELEMENT manuscripts (ms+)>

<!ELEMENT ms (name, bibliography*)>
<!ATTLIST ms
 abbrev CDATA #REQUIRED
 language CDATA #REQUIRED
 show CDATA #REQUIRED
>

<!ELEMENT name (#PCDATA | sup)*>

<!ELEMENT sup (#PCDATA)>

<!ELEMENT bibliography (#PCDATA | booktitle)*>

<!ELEMENT booktitle (#PCDATA)>

<!ELEMENT text (div+)>

<!ELEMENT div (div | unit)*>
<!ATTLIST div
 number CDATA #REQUIRED
 fragment CDATA #IMPLIED
>

<!ELEMENT unit (reading+)>
<!ATTLIST unit
 id CDATA #REQUIRED
 group CDATA "0"
 parallel CDATA #REQUIRED
>

<!ELEMENT reading (#PCDATA | w)*>
<!ATTLIST reading
 option CDATA #REQUIRED
 mss CDATA #REQUIRED
 linebreak CDATA #IMPLIED
 indent CDATA #IMPLIED
>

<!ELEMENT w (#PCDATA)>
<!ATTLIST w
 morph CDATA #IMPLIED
 lex CDATA #IMPLIED
 style CDATA #IMPLIED
 lang CDATA #IMPLIED
>

]>
<book filename="TAbA" title="Testament of Abraham Recension A">
  <version title="" author="">
    <divisions>
      <division label="Chapter" delimiter=":"/>
      <division label="Verse"/>
    </divisions>
    <manuscripts>
      <ms abbrev="Evans" language="Greek" show="no">
        <name>Craig A. Evans</name>
        <bibliography> M. R. James, The Testament of Abraham (Texts and Studies 2.1; Cambridge: Cambridge University Press, 1892); repr. in M. E. Stone (ed.), The Testament of Abraham: The Greek Recensions (SBLTT 2: Pseudepigrapha Series 2; Missoula: Scholars Press, 1972) 2-84.</bibliography>
      </ms>
    </manuscripts>
    <text>
      <div number="1">
        <div number="1">
          <unit id="1" group="0" parallel="">
            <reading option="0" mss="Evans ">Ἔζησεν Ἁβραὰμ τὸ μέτρον τῆς ζωῆς αὐτοῦ, ἔτη ἐννακόσια ἐνενήκοντα πέντε, πάντα δὲ τὰ ἔτη τῆς ζωῆς αὐτοῦ ζήσας ἐν ἡσυχίᾳ καὶ πραότητι καὶ δικαιοσύνῃ, πάνυ ὑπῆρχε φιλόξενος ὁ δίκαιος·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="2" group="0" parallel="">
            <reading option="0" mss="Evans ">πήξας γὰρ τὴν σκηνὴν αὐτοῦ ἐν τετραοδίῳ τῆς δρυὸς τῆς Μαμβρῆ, τοὺς πάντας ὑπεδέχετο, πλουσίους καὶ πένητας, βασιλεῖς τε καὶ ἄρχοντας, ἀναπήρους καὶ ἀδυνάτους, φίλους καὶ ξένους, γείτονας καὶ παροδίτας, ἴσον ὑπεδέχετο ὁ ὅσιος καὶ πανίερος καὶ δίκαιος καὶ φιλόξενος Ἁβραάμ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="3" group="0" parallel="">
            <reading option="0" mss="Evans ">ἔφθασεν δὲ καὶ ἐπὶ τοῦτον τὸ κοινὸν καὶ ἀπαραίτητον τοῦ θανάτου πικρὸν ποτήριον, καὶ τὸ ἄδηλον τοῦ βίου πέρας.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="4" group="0" parallel="">
            <reading option="0" mss="Evans ">προσκαλεσάμενος τοίνυν ὁ δεσπότης θεὸς τὸν ἀρχάγγελον αὐτοῦ Μιχαὴλ εἶπεν πρὸς αὐτόν· Κάτελθε, Μιχαὴλ ἀρχιστράτηγε, πρὸς Ἁβραάμ, καὶ εἰπὲ αὐτὸν περὶ τοῦ θανάτου, ἵνα διατάξεται περὶ τῶν πραγμάτων αὐτοῦ·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="5" group="0" parallel="">
            <reading option="0" mss="Evans ">ὅτι ηὐλόγησα αὐτὸν ὡς τοὺς ἀστέρας τοῦ οὐρανοῦ, καὶ ὡς τὴν ἄμμον τὴν παρὰ τὸ χεῖλος τῆς θαλάσσης· καὶ ἔστιν ἐν εὐπορίᾳ βίου πολλοῦ καὶ πραγμάτων πολλῶν, καὶ ὑπάρχει πλούσιος πάνυ· παρὰ πάντων δὲ δίκαιος ἐν πάσῃ ἀγαθωσύνῃ, φιλόξενος καὶ φιλόστοργος ἕως τέλους τῆς ζωῆς αὐτοῦ·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="6" group="0" parallel="">
            <reading option="0" mss="Evans ">σὺ δέ, ἀρχάγγελε Μιχαήλ, ἄπελθε πρὸς τὸν Ἁβραάμ, τὸν ἠγαπημένον μου φίλον, καὶ ἀνάγγειλον αὐτῷ περὶ τοῦ θανάτου αὐτοῦ, καὶ πληροφόρησον αὐτὸν ὅτι</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="7" group="0" parallel="">
            <reading option="0" mss="Evans ">Μέλλεις ἐν τῷ καιρῷ τούτῳ ἐξέρχεσθαι ἐκ τοῦ ματαίου κόσμου τούτου καὶ μέλλεις ἐκδημεῖν ἐκ τοῦ σώματος καὶ πρὸς τὸν ἴδιον δεσπότην ἐλεύσῃ ἐν ἀγαθοῖς.</reading>
          </unit>
        </div>
      </div>
      <div number="2">
        <div number="1">
          <unit id="8" group="0" parallel="">
            <reading option="0" mss="Evans ">Ἐξελθὼν δὲ ὁ ἀρχιστράτηγος ἐκ προσώπου τοῦ θεοῦ κατῆλθεν πρὸς τὸν Ἁβραὰμ ἐπὶ τὴν δρῦν τὴν Μαμβρῆ, καὶ εὗρεν τὸν δίκαιον Ἁβραὰμ ἐπὶ τὴν χώραν ἔγγιστα, ζεύγη βοῶν ἀροτριασμοῦ παρεδρεύοντα μετὰ τοὺς υἱοὺς Μασὲκ καὶ ἑτέροις παισὶν τὸν ἀριθμὸν δώδεκα· καὶ ἰδοὺ ὁ ἀρχιστράτηγος ἤρχετο πρὸς αὐτόν·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="9" group="0" parallel="">
            <reading option="0" mss="Evans ">ἰδὼν δὲ ὁ Ἁβραὰμ τὸν ἀρχιστράτηγον Μιχαὴλ μηκόθεν ἐρχόμενον, δίκην στρατιώτου εὐπρεπεστάτου, ἀναστὰς τοίνυν ὁ Ἁβραὰμ ὑπήντησεν αὐτῷ καθότι καὶ ἔθος εἶχεν, τοῖς ἐπιξένοις πᾶσιν προϋπαντῶν καὶ ὑποδεχόμενος·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="10" group="0" parallel="">
            <reading option="0" mss="Evans ">ὁ δὲ ἀρχιστράτηγος προχαιρετίσας αὐτὸν εἶπεν· Χαῖρε, τιμιώτατε πάτερ, δικαία ψυχὴ ἐκλεκτὴ τοῦ θεοῦ, φίλε γνήσιε τοῦ ἐπουρανίου.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="11" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραὰμ πρὸς τὸν ἀρχιστράτηγον· Χαῖρε, τιμιώτατε στρατιῶτα, ἡλιόρατε καὶ πανευπρεπέστατε ὑπὲρ πάντας τοὺς υἱοὺς τῶν ἀνθρώπων· καλῶς ἥκεις.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="12" group="0" parallel="">
            <reading option="0" mss="Evans ">τοῦτο χάριν αἰτοῦμαι τῆς σῆς παρουσίας πόθεν ἧκεν τὸ νέον τῆς ἡλικίας σου; δίδαξόν με τὸν σὸν ἱκέτην, πόθεν καὶ ἐκ ποίας στρατιᾶς καὶ ἐκ ποίας ὁδοῦ παραγέγονεν τὸ σὸν κάλλος;</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="13" group="0" parallel="">
            <reading option="0" mss="Evans ">ὁ δὲ ἀρχιστράτηγος ἔφη· Ἐγώ, δίκαιε Ἁβραάμ, ἀπὸ τῆς μεγάλης πόλεως ἔρχομαι· παρὰ τοῦ μεγάλου βασιλέως ἀπεστάλην διαδοχὴν φίλου αὐτοῦ γνησίου κομιζόμενος, ὅτι καὶ αὐτὸν ὁ βασιλεὺς προσκαλεῖται.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="14" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ὁ Ἁβραὰμ εἶπεν· Δεῦρο, κύριέ μου, πορεύθητι μετ᾽ ἐμοῦ ἕως τῆς χώρας μου. καὶ φησὶν ὁ ἀρχιστράτηγος· Ἔρχομαι.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="15" group="0" parallel="">
            <reading option="0" mss="Evans ">ἀπελθόντος δὲ ἐν τῇ χώρᾳ τοῦ ἀροτριασμοῦ ἐκαθέσθησαν πρὸς ὁμιλίαν.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="16" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραὰμ τοῖς παισὶν αὐτοῦ τοῖς υἱοῖς Μασέκ· Ἀπέλθατε εἰς τὴν ἀγέλην τῶν ἵππων καὶ ἐνέγκατε δύο ἵππους εὐμενεῖς καὶ ἡμέρους δεδαμασμένους ὅπως ἐγκαθεσθῶμεν ἐγώ τε καὶ ὁ ἄνθρωπος οὗτος ὁ ἐπίξενος.</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="17" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ εἶπεν ὁ ἀρχιστράτηγος· Μὴ, κύριέ μου Ἁβραὰμ, μὴ ἐνέγκωσιν ἵππους, ὅτι ἀπέρχομαι τούτου, τοῦ μὴ καθίσαι ἐπὶ ζῴου τετραπόδου ποτέ·</reading>
          </unit>
        </div>
        <div number="11">
          <unit id="18" group="0" parallel="">
            <reading option="0" mss="Evans ">μὴ γὰρ ὁ ἐμὸς βασιλεῦς οὐκ ἦν πλούσιος ἐν ἐμπορίᾳ πολλῇ, ἔχων ἐξουσίαν καὶ ἀνθρώποις καὶ κτήνεσιν παντοίοις; ἀλλ᾽ ἐγὼ ἀπέχομαι τούτου, τοῦ μὴ καθίσαι ἐπὶ ζῴου τετραπόδου ποτέ·</reading>
          </unit>
        </div>
        <div number="12">
          <unit id="19" group="0" parallel="">
            <reading option="0" mss="Evans ">ἀπέλθωμεν οὖν, δικαία ψυχή, πεζεύοντες ἕως τοῦ οἴκου σου μετεωριζόμενοι. καὶ εἶπεν Ἁβραάμ· Ἀμήν, γένοιτο.</reading>
          </unit>
        </div>
      </div>
      <div number="3">
        <div number="1">
          <unit id="20" group="0" parallel="">
            <reading option="0" mss="Evans ">Ἀπερχομένων δὲ αὐτῶν ἀπὸ τοῦ ἀγροῦ πρὸς τὸν οἶκον αὐτοῦ,</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="21" group="0" parallel="">
            <reading option="0" mss="Evans ">κατὰ τῆς ὁδοῦ ἐκείνης ἵστατο δένδρον κυπάρισσος·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="22" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ κατὰ πρόσταξιν τοῦ θεοῦ ἐβόησεν τὸ δένδρον ἀνθρωπίνῃ φωνῇ, καὶ εἶπεν· Ἅγιος, ἅγιος, ἅγιος κύριος ὁ θεὸς ὁ προσκαλούμενος αὐτὸν τοῖς ἀγαπῶσιν αὐτόν.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="23" group="0" parallel="">
            <reading option="0" mss="Evans ">ἔκρυψεν δὲ Ἁβραὰμ τὸ μυστήριον, νομίσας ὅτι ὁ ἀρχιστράτηγος τὴν φωνὴν τοῦ δένδρου οὐκ ἤκουσεν.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="24" group="0" parallel="">
            <reading option="0" mss="Evans ">ἐλθόντες δὲ πλησίον τοῦ οἴκου ἐν τῇ αὐλῇ ἐκαθέσθησαν· καὶ ἰδὼν ὁ Ἰσαὰκ τὴν πρόσωψιν τοῦ ἀγγέλου εἶπεν πρὸς Σάρραν τὴν μητέρα αὐτοῦ· Κυρία μου μῆτερ, ἰδοὺ ὁ ἄνθρωπος ὁ καθεζόμενος μετὰ τοῦ πατρός μου Ἁβραὰμ υἱὸς οὐκ ἔστιν ἀπὸ τοῦ γένους τῶν κατοικούντων ἐπὶ τῆς γῆς.</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="25" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ἔδραμεν Ἰσαάκ, καὶ προσεκύνησεν αὐτὸν καὶ προσέπεσεν τοῖς ποσὶν τοῦ ἀσωμάτου· καὶ ὁ ἀσώματος ηὐλόγησεν αὐτὸν καὶ εἶπεν· Χαρίσεταί σοι κύριος ὁ θεὸς τὴν ἐπαγγελίαν αὐτοῦ ἣν ἐπηγγείλατο τῷ πατρί σου Ἁβραὰμ καὶ τῷ σπέρματι αὐτοῦ, καὶ χαρίσεταί σοι καὶ τὴν τιμίαν εὐχὴν τοῦ πατρός σου καὶ τῆς μητρός σου.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="26" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραὰμ πρὸς Ἰσαὰκ τὸν υἱὸν αὐτοῦ· Τέκνον Ἰσαάκ, ἄντλησον ὕδωρ ἀπὸ τοῦ φρέατος καὶ ἔνεγκέ μοι ἐπὶ τῆς λεκάνης ἵνα νίψωμεν τοῦ ἀνθρώπου τούτου τοῦ ἐπιξένου τοὺς πόδας, ὅτι ἀπὸ μακρᾶς ὁδοῦ πρὸς ἡμᾶς ἐλθὼν ἐκοπίασεν.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="27" group="0" parallel="">
            <reading option="0" mss="Evans ">δραμὼν δὲ Ἰσαὰκ εἰς τὸ φρέαρ ἤντλησεν ὕδωρ ἐπὶ τῆς λεκάνης καὶ ἤνεγκεν πρὸς αὐτούς·</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="28" group="0" parallel="">
            <reading option="0" mss="Evans ">προσελθὼν δὲ Ἁβραὰμ ἔνιψεν τοὺς πόδας τοῦ ἀρχιστρατήγου Μιχαήλ· ἐκινήθησαν δὲ τὰ σπλάγχνα τοῦ Ἁβραὰμ καὶ ἐδάκρυσεν ἐπὶ τὸν ξένον.</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="29" group="0" parallel="">
            <reading option="0" mss="Evans ">ἰδὼν δὲ Ἰσαὰκ τὸν πατέρα αὐτοῦ κλαίοντα, ἔκλαυσεν καὶ αὐτός· ἰδὼν δὲ ὁ ἀρχιστράτηγος αὐτοὺς κλαίοντας συνεδάκρυσεν καὶ αὐτὸς μετ᾽ αὐτῶν,</reading>
          </unit>
        </div>
        <div number="11">
          <unit id="30" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ἔπιπτον τὰ δάκρυα τοῦ ἀρχιστρατήγου ἐπὶ τῆς λεκάνης εἰς τὸ ὕδωρ τοῦ νιπτῆρος, καὶ ἐγένοντο λίθοι πολύτιμοι·</reading>
          </unit>
        </div>
        <div number="12">
          <unit id="31" group="0" parallel="">
            <reading option="0" mss="Evans ">ἰδὼν δὲ ὁ Ἁβραὰμ τὸ θαῦμα καὶ ἐκπλαγεὶς ἔλαβεν τοὺς λίθους κρυφαίως καὶ ἔκρυψεν τὸ μυστήριον, μόνος ἔχων ἐν τῇ καρδίᾳ αὐτοῦ.</reading>
          </unit>
        </div>
      </div>
      <div number="4">
        <div number="1">
          <unit id="32" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραὰμ πρὸς Ἰσαὰκ τὸν υἱὸν αὐτοῦ· Ἄπελθε, υἱέ μου ἀγαπητὲ, εἰς τὸ ταμεῖον τοῦ τρικλίνου καὶ καλλώπισον αὐτό•</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="33" group="0" parallel="">
            <reading option="0" mss="Evans ">στρῶσον δὲ ἡμῖν ἐκεῖ δύο κλινάρια, ἕνα ἐμὸν καὶ ἕνα τοῦ ἀνθρώπου τούτου τοῦ ἐπιξενισθέντος ἡμῖν σήμερον· ἑτοίμασον δὲ ἡμῖν ἐκεῖ δίφρον καὶ λυχνίαν καὶ τράπεζαν ἐν ἀφθονίᾳ παντὸς ἀγαθοῦ· καλλώπισον τὸ οἴκημα, τέκνον, καὶ ὑφάπλωσον σινδόνας καὶ πορφύραν καὶ βύσσον· θυμίασον πᾶν τίμιον καὶ ἔνδοξον θυμίαμα, καὶ βοτάνας εὐόσμους ἐκ τοῦ παραδείσου ἐνέγκας πλήρωσον τὸν οἶκον ἡμῶν•</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="34" group="0" parallel="">
            <reading option="0" mss="Evans ">ἄναψον λύχνους ἑπτὰ διελαίους ὅπως εὐφρανθῶμεν, ὅτι ὁ ἀνὴρ οὗτος ὁ ἐπιξενισθεὶς ἡμῖν σήμερον ἐνδοξότερος ὑπάρχει βασιλέων καὶ ἀρχόντων, ὅτι καὶ ἡ ὅρασις αὐτοῦ ὑπερφέρει πάντας τοὺς υἱοὺς τῶν ἀνθρώπων.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="35" group="0" parallel="">
            <reading option="0" mss="Evans ">ὁ δὲ Ἰσαὰκ ἡτοίμασεν πάντα καλῶς· παραλαβὼν δὲ Ἁβραὰμ τὸν ἀρχάγγελον Μιχαήλ, ἀνῆλθεν ἐν τῷ οἰκήματι τοῦ τρικλίνου, καὶ ἐκαθέσθησαν ἀμφότεροι ἐπὶ τὰ κλινάρια, μέσον δὲ αὐτῶν προῆγε τράπεζαν ἐν ἀφθονίᾳ παντὸς ἀγαθοῦ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="36" group="0" parallel="">
            <reading option="0" mss="Evans ">ἐγερθεὶς οὖν ἀρχιστράτηγος ἐξῆλθεν ἔξω, ὡς δῆθεν γαστρὸς χρείᾳ ὕδατος χύσιν ποιῆσαι, καὶ ἀνῆλθεν εἰς τὸν οὐρανὸν ἐν ῥιπῇ ὀφθαλμοῦ καὶ ἔστη ἐνώπιον τοῦ θεοῦ, καὶ εἶπεν πρὸς αὐτόν·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="37" group="0" parallel="">
            <reading option="0" mss="Evans ">Δέσποτα κύριε, ἵνα γινώσκῃ τὸ σὸν κράτος ὅτι ἐγὼ τὴν μνήμην τοῦ θανάτου πρὸς τὸν δίκαιον ἄνδρα ἐκεῖνον ἀναγγεῖλαι οὐ δύναμαι, ὅτι οὐκ εἶδον ἐπὶ τῆς γῆς ἄνθρωπον ὅμοιον αὐτοῦ, ἐλεήμονα, φιλόξενον, δίκαιον, ἀληθινὸν, θεοσεβῆ, ἀπεχόμενον ἀπὸ παντὸς πονηροῦ πράγματος· καὶ νῦν γίνωσκε, κύριε, ὅτι ἐγὼ τὴν μνείαν τοῦ θανάτου ἀναγγεῖλαι οὐ δύναμαι.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="38" group="0" parallel="">
            <reading option="0" mss="Evans ">ὁ δὲ κύριος εἶπεν· Κάτελθε, Μιχαὴλ ἀρχιστράτηγε, πρὸς τὸν φίλον μου Ἁβραὰμ, καὶ ὅτι ἐὰν λέγῃ σοι, τοῦτο καὶ ποίει. καὶ ὅτι ἐὰν ἐσθίῃ, ἔσθιε καὶ σὺ μετ᾽ αὐτοῦ· ἐγὼ δὲ ἐπιβαλῶ τὸ πνεῦμά μου τὸ ἅγιον ἐπὶ τὸν υἱὸν αὐτοῦ Ἰσαὰκ,</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="39" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ῥίψω τὴν μνήμην τοῦ θανάτου αὐτοῦ εἰς τὴν καρδίαν τοῦ Ἰσαὰκ, ἵνα καὶ αὐτὸς ἐν ὀνείρῳ θεάσηται τὸν θάνατον τοῦ πατρὸς αὐτοῦ, καὶ Ἰσαὰκ δὲ ἀναγγελεῖ τὸ ὅραμα, σὺ δὲ διακρινεῖς· καὶ αὐτὸς γνώσεται τὸ τέλος αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="40" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ὁ ἀρχιστράτηγος εἶπεν· Κύριε, πάντα τὰ ἐπουράνια πνεύματα ὑπάρχουσιν ἀσώματα, καὶ οὔτε ἐσθίουσιν οὔτε πίνουσιν· καὶ οὗτος δὲ ἐμοὶ τράπεζαν παρέθετο ἐν ἀφθονίᾳ πάντων ἀγαθῶν τῶν ἐπιγείων καὶ φθαρτῶν· καὶ νῦν, κύριε, τί ποιήσω; πῶς διαλάθωμαι τοῦτον, καθήμενος ἐν μιᾷ τραπέζῃ μετ᾽ αὐτοῦ;</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="41" group="0" parallel="">
            <reading option="0" mss="Evans ">ὁ δὲ κύριος εἶπεν· Κάτελθε πρὸς αὐτόν, καὶ περὶ τούτου μή σοι μελείτω· καθεζομένου γὰρ σοῦ μετ᾽ αὐτοῦ ἐγὼ ἀποστελῶ ἐπί σε πνεῦμα παμφάγον, καὶ ἀναλίσκει ἐκ τῶν χειρῶν σου καὶ διὰ τοῦ στόματός σου πάντα τὰ ἐπὶ τῆς τραπέζης· καὶ συνευφράνθητι μετ᾽ αὐτοῦ ἐν πᾶσιν·</reading>
          </unit>
        </div>
        <div number="11">
          <unit id="42" group="0" parallel="">
            <reading option="0" mss="Evans ">μόνον τὰ τοῦ ὁράματος διακρινεῖς καλῶς ὅπως ἂν γνώσεται Ἁβραὰμ τὴν τοῦ θανάτου δρεπάνην, καὶ τὸ τοῦ βίου ἄδηλον πέρας, καὶ ἵνα ποιήσῃ διάταξιν περὶ πάντων τῶν ὑπαρχόντων αὐτοῦ, ὅτι ηὐλόγησα αὐτὸν ὑπὲρ ἄμμον θαλάσσης, καὶ ὡς τοὺς ἀστέρας τοῦ οὐρανοῦ.</reading>
          </unit>
        </div>
      </div>
      <div number="5">
        <div number="1">
          <unit id="43" group="0" parallel="">
            <reading option="0" mss="Evans ">Τότε ὁ ἀρχιστράτηγος κατῆλθεν εἰς τὸν οἶκον τοῦ Ἁβραὰμ καὶ ἐκαθέσθη μετ᾽ αὐτοῦ ἐν τῇ τραπέζῃ, Ἰσαὰκ δὲ ὑπηρέτει αὐτοῖς•</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="44" group="0" parallel="">
            <reading option="0" mss="Evans ">τελεσθέντος δὲ τοῦ δείπνου ἐποίησεν Ἁβραὰμ τὴν κατὰ ἔθος εὐχήν, καὶ ὁ ἀρχάγγελος ηὔχετο μετ᾽ αὐτοῦ, καὶ ἀνεπαύσαντο ἕκαστος εἰς τὴν κλίνην αὐτοῦ.</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="45" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἰσαὰκ πρὸς τὸν πατέρα αὐτοῦ· Πάτερ, ἤθελα κἀγὼ ἀναπαῆναι μεθ᾽ ὑμῶν ἐν τῷ τρικλίνῳ τούτῳ, ἵνα ἀκούσω κἀγὼ τὰ διαλεγόμενα ὑμῶν· ἀγαπῶ γὰρ ἀκούειν τὴν διαφορὰν τῆς ὁμιλίας τοῦ παναρέτου ἀνδρὸς τούτου.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="46" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραάμ· Οὐχὶ, τέκνον, ἀλλὰ ἄπελθε ἐν τῷ σῷ τρικλίνῳ καὶ ἀναπαύσαι ἐν τῇ κλίνῃ σου, ἵνα μὴ γινώμεθα ἐπιβαρεῖς τῷ ἀνθρώπῳ τούτῳ.</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="47" group="0" parallel="">
            <reading option="0" mss="Evans ">τότε Ἰσαὰκ λαβὼν τὴν εὐχὴν παρ᾽ αὐτῶν, καὶ εὐλογήσας, ἀπῆλθεν ἐν τῷ ἰδίῳ τρικλίνῳ καὶ ἀνέπεσεν ἐπὶ τὴν κλινὴν αὐτοῦ•</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="48" group="0" parallel="">
            <reading option="0" mss="Evans ">ἔρριψεν δὲ ὁ θεὸς τὴν μνήμην τοῦ θανάτου εἰς τὴν καρδίαν τοῦ Ἰσαὰκ ὡς ἐν ὀνείροις·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="49" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ περὶ ὥραν τρίτην τῆς νυκτὸς διυπνισθεὶς Ἰσαὰκ ἀνέστη ἀπὸ τῆς κλίνης αὐτοῦ καὶ ἦλθεν δρομαίως ἕως τοῦ τρικλίνου ἔνθα ὁ πατὴρ αὐτοῦ ἦν κοιμώμενος μετὰ τοῦ ἀρχαγγέλου.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="50" group="0" parallel="">
            <reading option="0" mss="Evans ">φθάσας οὖν Ἰσαὰκ πρὸς τὴν θύραν ἔκραζεν λέγων· Πάτερ Ἁβραάμ, ἀναστὰς ἄνοιξόν μοι ταχέως, ὅπως εἰσέλθω καὶ κρεμασθῶ ἐν τῷ τραχήλῳ σου καὶ ἀσπάσωμαί σε πρὶν ἤ σε ἀροῦσιν ἀπ᾽ ἐμοῦ.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="51" group="0" parallel="">
            <reading option="0" mss="Evans ">ἀναστὰς οὖν Ἁβραὰμ ἤνοιξεν αὐτῷ· εἰσελθὼν δὲ Ἰσαὰκ ἐκρεμάσθη ἐπὶ τὸν τράχηλον αὐτοῦ, καὶ ἤρξατο κλαίειν φωνῇ μεγάλῃ.</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="52" group="0" parallel="">
            <reading option="0" mss="Evans ">συγκινηθεὶς οὖν τὰ σπλάγχνα ὁ Ἁβραὰμ ἔκλαυσεν καὶ αὐτὸς μετ᾽ αὐτοῦ φωνῇ μεγάλῃ. ἰδὼν δὲ ὁ ἀρχιστράτηγος αὐτοὺς κλαίοντας, ἔκλαυσεν καὶ αὐτός.</reading>
          </unit>
        </div>
        <div number="11">
          <unit id="53" group="0" parallel="">
            <reading option="0" mss="Evans ">Σάρρα δὲ ὑπάρχουσα ἐν τῇ σκηνῇ αὐτῆς ἤκουσεν τοῦ κλαυθμοῦ αὐτῶν καὶ ἦλθεν δρομαία ἐπ᾽ αὐτοὺς, καὶ εὗρεν αὐτοὺς περιπλακομένους καὶ κλαίοντας·</reading>
          </unit>
        </div>
        <div number="12">
          <unit id="54" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ εἶπεν Σάρρα μετὰ κλαυθμοῦ· Κύριέ μου Ἁβραάμ, τί ἐστιν τοῦτο ὅτι κλαίετε; ἀνάγγειλόν μοι, κύριέ μου,</reading>
          </unit>
        </div>
        <div number="13">
          <unit id="55" group="0" parallel="">
            <reading option="0" mss="Evans ">μὴ οὗτος ὁ ἀδελφὸς ὁ ἐπιξενισθεὶς ἡμῖν σήμερον φάσιν ἤνεγκέν σοι περὶ τοῦ ἀδελφιδοῦ σου Λὼτ, ὅτι ἀπέθανεν, καὶ διὰ τοῦτο πενθεῖτε οὕτως;</reading>
          </unit>
        </div>
        <div number="14">
          <unit id="56" group="0" parallel="">
            <reading option="0" mss="Evans ">ὑπολαβὼν δὲ ὁ ἀρχιστράτηγος εἶπον πρὸς αὐτήν· Οὐχὶ, ἀδελφὴ Σάρρα, οὐκ ἔστιν οὕτως ὡς σὺ λέγεις· ἀλλὰ ὁ υἱός σου Ἰσαὰκ, ὡς ἐμοὶ δοκεῖ, ὄνειρον ἐθεάσατο, καὶ ἦλθεν πρὸς ἡμᾶς κλαίων, καὶ ἡμεῖς τοῦτον ἰδόντες τὰ σπλάγχνα συνεκινήθημεν, καὶ ἐκλαύσαμεν.</reading>
          </unit>
        </div>
      </div>
      <div number="6">
        <div number="1">
          <unit id="57" group="0" parallel="">
            <reading option="0" mss="Evans ">Ἀκούσασα δὲ Σάρρα τὴν διαφορὰν τῆς ὁμιλίας τοῦ ἀρχιστρατήγου, εὐθὺς ἐγνώρισεν ὅτι ἄγγελος κυρίου ἐστὶν ὁ λαλῶν·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="58" group="0" parallel="">
            <reading option="0" mss="Evans ">συννεύει οὖν ἡ Σάρρα τὸν Ἁβραὰμ τὰ πρὸς τὴν θύραν ἔξω ἐλθεῖν, καὶ λέγει αὐτῷ· Κύριέ μου Ἁβραὰμ, σὺ γινώσκεις τίς ἐστιν οὗτος ὁ ἀνήρ;</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="59" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραάμ· Οὐ γινώσκω.</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="60" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Σάρρα· Ἐπίστασαι, κύριέ μου, τοὺς τρεῖς ἄνδρας τοὺς ἐπουρανίους τοὺς ἐπιξενισθέντας ἐν τῇ σκηνῇ ἡμῶν παρὰ τὴν δρῦν τὴν Μαμβρῆ ὅτε ἔσφαξας τὸν μόσχον τὸν ἄμωμον καὶ παρέθηκας αὐτοῖς τράπεζαν·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="61" group="0" parallel="">
            <reading option="0" mss="Evans ">δαπανηθέντων δὲ τῶν κρεάτων, ἠγέρθη πάλιν ὁ μόσχος καὶ ἐθήλαζεν τὴν μητέρα αὐτοῦ ἐν ἀγαλλιάσει· οὐκ οἶδας, κύριέ μου Ἁβραὰμ, ὅτι καὶ καρπὸν κοιλίας ἐξ ἐπαγγελίας ἡμῖν ἐδωρήσαντο τὸν Ἰσαάκ; ἐκ γὰρ τῶν τριῶν ἁγίων ἀνδρῶν ἐκείνων οὗτος ἐστὶν ὁ εἷς ἐξ αὐτῶν.</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="62" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραάμ· Ὦ Σάρρα, τοῦτο ἀληθὲς εἴρηκας· δόξα καὶ εὐλογία παρὰ θεοῦ καὶ πατρός· καὶ γὰρ ἐγὼ τῇ ὀψὲ βραδείᾳ, ὅτε ἔνιπτον τοὺς πόδας αὐτοῦ ἐν τῇ λεκάνῃ τοῦ νιπτῆρος εἶπον ἐν τῇ καρδίᾳ μου· Οὗτοι οἱ πόδες ἐκ τῶν τριῶν ἀνδρῶν εἰσὶν οὓς ἔνιψα τότε.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="63" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ τὰ δάκρυα αὐτοῦ ὀψὲ ἐν τῷ νιπτῆρι πίπτοντα ἐγένοντο λίθοι τίμιοι. καὶ ἐκβαλὼν ἐκ τοῦ κόλπου αὐτοῦ δέδωκεν αὐτὰ τῇ Σάρρᾳ, λέγων· Εἰ ἀπιστεῖς μοι, νῦν θέασαι ταῦτα.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="64" group="0" parallel="">
            <reading option="0" mss="Evans ">λαβοῦσα δὲ αὐτὰ ἡ Σάρρα προσεκύνησεν καὶ ἠσπάσατο καὶ εἶπεν· Δόξα τῷ θεῷ τῷ δεικνύοντι ἡμῖν θαυμάσια· καὶ νῦν γίνωσκε, κύριέ μου Ἁβραάμ, ὅτι ἀποκάλυψίς τινος ἔργου ἐστὶν ἐν ἡμῖν, κἄν τε πονηρὸν κἄν τε ἀγαθόν.</reading>
          </unit>
        </div>
      </div>
      <div number="7">
        <div number="1">
          <unit id="65" group="0" parallel="">
            <reading option="0" mss="Evans ">Καταλιπὼν δὲ Ἁβραὰμ τὴν Σάρραν εἰσῆλθεν ἐν τῷ τρικλίνῳ καὶ εἶπεν πρὸς Ἰσαάκ· Δεῦρο, υἱέ μου ἀγαπητέ, ἀνάγγειλόν μοι τὴν ἀλήθειαν, τί τὰ ὁραθέντα καὶ τί πέπονθας ὅτι οὕτω δρομαίως εἰσῆλθες πρὸς ἡμᾶς;</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="66" group="0" parallel="">
            <reading option="0" mss="Evans ">ὑπολαβὼν δὲ Ἰσαὰκ ἤρξατο λέγειν· Εἶδον ἐγώ, κύριέ μου, τῇ νυκτὶ ταύτῃ τὸν ἥλιον καὶ τὴν σελήνην ὑπεράνω τῆς κεφαλῆς μου, καὶ τὰς ἀκτῖνας αὐτοῦ κυκλοῦντα καὶ φωταγωγοῦντά με·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="67" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ταῦτα οὕτως ἐμοῦ θεωροῦντος καὶ ἀγαλλιωμένου, εἶδον τὸν οὐρανὸν ἀνεῳγότα, καὶ εἶδον ἄνδρα φωτοφόρον ἐκ τοῦ οὐρανοῦ κατελθόντα ὑπὲρ ἑπτὰ ἡλίους ἀστράπτοντα·</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="68" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ ἐλθὼν ὁ ἀνὴρ ὁ ἡλιόμορφος ἐκεῖνος ἔλαβεν τὸν ἥλιον ἀπὸ τῆς κεφαλῆς μου, καὶ ἀνῆλθεν εἰς τοὺς οὐρανοὺς ὅθεν καὶ ἐξῆλθεν·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="69" group="0" parallel="">
            <reading option="0" mss="Evans ">ἐγὼ δὲ ἐλυπήθην μεγάλως ὅτι ἔλαβεν τὸν ἥλιον ἀπ᾽ ἐμοῦ· καὶ μετ᾽ ὀλίγον ὡς ἔτι ἐμοῦ λυπουμένου καὶ ἀδημονοῦντος, εἶδον τὸν ἄνδρα ἐκεῖνον ἐκ δευτέρου ἐκ τοῦ οὐρανοῦ ἐξελθόντα· καὶ ἔλαβεν ἀπ᾽ ἐμοῦ καὶ τὴν σελήνην ἐκ τῆς κεφαλῆς μου·</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="70" group="0" parallel="">
            <reading option="0" mss="Evans ">ἔκλαυσα δὲ μεγάλως καὶ παρεκάλεσα τὸν ἄνδρα ἐκεῖνον τὸν φωτοφόρον καὶ εἶπον· Μὴ, κύριέ μου, μὴ ἄρῃς τὴν δόξαν μου ἀπ᾽ ἐμοῦ, ἐλέησόν με καὶ εἰσάκουσόν μου· καὶ κἄν τὸν ἥλιον ἄρας ἀπ᾽ ἐμοῦ, κἄν τὴν σελήνην ἔασον ἐπ᾽ ἐμέ.</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="71" group="0" parallel="">
            <reading option="0" mss="Evans ">αὐτὸς δὲ εἶπεν· Ἄφες ἀναληφθῆναι αυτοὺς πρὸς τὸν ἄνω βασιλέα, ὅτι θέλει αὐτοὺς ἐκεῖ. καὶ ἦρεν αὐτοὺς ἀπ᾽ ἐμοῦ, τὰς δὲ ἀκτῖνας ἔασεν ἐπ᾽ ἐμέ.</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="72" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ ὁ ἀρχιστράτηγος· Ἄκουσον, δίκαιε Ἁβραάμ· ὁ ἥλιος ὃν ἑώρακεν ὁ παῖς σου, σὺ εἶ, ὁ πατὴρ αὐτοῦ· καὶ ἡ σελήνη ὁμοίως ἡ μήτηρ αὐτοῦ Σάρρα ὑπάρχουσα· ὁ δὲ ἀνὴρ ὁ φωτοφόρος ὁ ἐκ τοῦ θεοῦ οὐρανοῦ καταβάς, οὗτός ἐστιν ὁ ἐκ τοῦ θεοῦ ἀποσταλεὶς, ὁ μέλλων λαβεῖν τὴν δικαίαν σου ψυχὴν ἀπό σου.</reading>
          </unit>
        </div>
        <div number="9">
          <unit id="73" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ νῦν γίνωσκε, τιμιώτατε Ἁβραάμ, ὅτι μέλλεις ἐν τῷ καιρῷ τούτῳ καταλιπεῖν τὸν κοσμικὸν βίον καὶ πρὸς τὸν θεὸν ἐκδημεῖν.</reading>
          </unit>
        </div>
        <div number="10">
          <unit id="74" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ Ἁβραὰμ πρὸς τὸν ἀρχιστράτηγον· Ὦ θαῦμα θαυμάτων καινότερον! καὶ λοιπὸν σὺ εἶ ὁ μέλλων λαβεῖν τὴν ψυχήν μου ἀπ᾽ ἐμοῦ;</reading>
          </unit>
        </div>
        <div number="11">
          <unit id="75" group="0" parallel="">
            <reading option="0" mss="Evans ">λέγει αὐτῷ ὁ ἀρχιστράτηγος· Ἐγώ εἰμι Μιχαὴλ ὁ ἀρχιστράτηγος ὁ παρεστηκὼς ἐνώπιον τοῦ θεοῦ, καὶ ἀπεστάλην πρός σε ὅπως ἀναγγείλω σοι τὴν τοῦ θανάτου μνήμην· καὶ εἴθ᾽ οὕτως ἀπελεύσομαι πρὸς αὐτὸν καθὼς ἐκελεύσθημεν.</reading>
          </unit>
        </div>
        <div number="12">
          <unit id="76" group="0" parallel="">
            <reading option="0" mss="Evans ">καὶ εἶπεν Ἁβραάμ· Νῦν ἔγνωκα ἐγὼ ὅτι ἄγγελος κυρίου εἶ σὺ, καὶ ἀπεστάλης λαβεῖν τὴν ψυχήν μου· ἀλλ᾽ οὐ μή σοι ἀκολουθήσω· ἀλλ᾽ ὅπερ κελεύει[ς] ποίησον.</reading>
          </unit>
        </div>
      </div>
      <div number="8">
        <div number="1">
          <unit id="77" group="0" parallel="">
            <reading option="0" mss="Evans ">Ὁ δὲ ἀρχιστράτηγος ἀκούσας τὸ ῥῆμα τοῦτο, εὐθέως ἀφανὴς ἐγένετο· καὶ ἀνελθὼν εἰς τὸν οὐρανὸν ἔστη ἐνώπιον τοῦ θεοῦ καὶ ἀνήγγειλεν πάντα ὅσα εἶδεν εἰς τὸν οἶκον Ἁβραάμ·</reading>
          </unit>
        </div>
        <div number="2">
          <unit id="78" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ καὶ τοῦτο ὁ ἀρχιστράτηγος πρὸς τὸν δεσπότην ὅτι Καὶ τοῦτο λέγει ὁ φίλος σου Ἁβραὰμ ὅτι Οὐ μή σοι ἀκολουθήσω, ἀλλ᾽ ὅπερ κελεύει[ς] ποίησον·</reading>
          </unit>
        </div>
        <div number="3">
          <unit id="79" group="0" parallel="">
            <reading option="0" mss="Evans ">ἀρτίως δέσποτα παντοκράτωρ, εἴ τι κελεύει ἡ σὴ δόξα καὶ ἡ βασιλεία ἡ ἀθάνατος;</reading>
          </unit>
        </div>
        <div number="4">
          <unit id="80" group="0" parallel="">
            <reading option="0" mss="Evans ">εἶπεν δὲ ὁ θεὸς πρὸς τὸν ἀρχιστράτηγον Μιχαήλ· Ἄπελθε πρὸς τὸν φίλον μου Ἁβραὰμ ἔτι ἅπαξ καὶ εἶπε αὐτῷ οὕτως·</reading>
          </unit>
        </div>
        <div number="5">
          <unit id="81" group="0" parallel="">
            <reading option="0" mss="Evans ">ὅτι Τάδε λέγει κύριος ὁ θεός σου, ὁ εἰσαγαγών σε ἐν τῇ γῇ τῆς ἐπαγγελίας, ὁ εὐλογήσας σε ὑπὲρ τὴν ἄμμον τῆς θαλάσσης καὶ ὑπὲρ τοὺς ἀστέρας τοῦ οὐρανοῦ,</reading>
          </unit>
        </div>
        <div number="6">
          <unit id="82" group="0" parallel="">
            <reading option="0" mss="Evans ">ὁ διανοίξας μήτραν Σάρρας τῆς στειρώσης καὶ χαρισάμενός σοι καρπὸν κοιλίας ἐν γήρει τὸν Ἰσαάκ·</reading>
          </unit>
        </div>
        <div number="7">
          <unit id="83" group="0" parallel="">
            <reading option="0" mss="Evans ">Ἀμὴν λέγω σοι ὅτι εὐλογῶν εὐλογήσω σε καὶ πληθύνων πληθυνῶ τὸ σπέρμα σου, καὶ δώσω σοι πάντα ὅσα ἂν αἰτήσῃς παρ᾽ ἐμοῦ, ὅτι ἐγώ εἰμι κύριος ὁ θεός σου, καὶ πλὴν ἐμοῦ οὐκ ἔστιν ἄλλος·</reading>
          </unit>
        </div>
        <div number="8">
          <unit id="84" group="0" parallel="">